apiVersion: v1
kind: Secret
metadata:
    name: hermes-ssh-key
    namespace: hermes-agent
type: Opaque
stringData:
    id_rsa: ENC[AES256_GCM,data:KOUK+uFbiaeZVVM49Tpv8MUGZXcIMrns7zleFQSEFkUGWNHfqIT1ZQrBNRQNOhrlmV93tVCWNQ4WcElP1kg4yQA2HMhuKBSwnG0nhjvEO5g6eNHjGyUiuEkCV7x/1D1YABrkzw9ngA8LdYtVn5Rknq9J2oe3z7cb/dEVkm9H+/jJio/AtkJMdGkVmXlKdwPfNepX7F3rLlV7xPLcQW0cKGLgjvI151iYNt7ry9/T9Q9MjC2rOHvsBHGbmMWCbVX5uLoH/vM3HHrFxvf35htyed6/KV74nB748scNfOyk/3WZnv0Rf2eWzmLvfuSPIMsi4AR+w5d0PqQUhQApU2+/7NCWp1SrBQkvvzAmGbnJ1PcaKqOpMj9DfwtfBMdKIbQeOHtSZKhcfcStFBk9b4MhQCO/zxWvsRkPSYAfLuPul3bXoOjJYiFf7M+VVniDri81Ob2fSs9pHGFQPgOgPwqbCWWMPvGCczenkLomgPqLPmN9S5n9IaIJbDoU7l5rfkkvkM/4,iv:AWo0dsuX0x/2h6vsFEh+juAX1A6yE9/1Pxc+Qu++KqI=,tag:68w9Lca2XzZF3WdxKeytuw==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNkoyQTVMWnR3L1VJV28w
            MnhuUjlDUU4zNGlZZjFQNktXOW1SU09IQjBjClBMQU1DZmJSZWdCT2xTSGhOWlVD
            M1pIZVRIelhBV29qZ08vVlRhcElrY2sKLS0tIG95eDNZdHZOVzhQU1prb040QlBY
            aHIxSDA2bC9NMU1mV3RHdFBBbklhMjgKuof/izVC7J/xdkbT7wnfMOCuzInVp4DJ
            3GXNL5RbGlJ4sVHAfngffuy1RskFeboFsoH4ZE055lAa44W75ZhLIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T07:37:51Z"
    mac: ENC[AES256_GCM,data:O5G+iMjJWJ/Vgw+8YZx2ennUNhtlGl9v/S4YfBY8HIuO+nXlICL6uVM6dtVNKnfZ7C89i8JnQ+OBGKiud9F7abv5gZZ088ystrWyzqOHbqbseCauakLZhdvyVuuAYkszTy6eAx6n/d2g8Vzwm3vZbIkj9uLvpWhEV39lBu+2Htg=,iv:ommrOXeWlCEtibIp28N6L1Gteabt7a1uQIkC7tt/ni8=,tag:JX7m/E0WIm1/nJyrLMWKnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
