apiVersion: v1
kind: Secret
metadata:
    name: garage-credentials
    namespace: garage
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:6ZIjQaNocMJuEDI=,iv:LB5AedxyTU/V+ixRVTKz1zvCflsA/tlRMHUsVlk48Zs=,tag:Asvb2W+NzxBrOjJthcOi5A==,type:str]
    rootPassword: ENC[AES256_GCM,data:zRwFqGei+BjbadCsSoqIuhFbsjn36UdkqlobwmDllFGjgi06O4wv9XVX/Mpsi1DY,iv:IZdXAUkJZwRm8l5zxDwJdbuIUSqM0L6xzoNVOE7ZCnI=,tag:sif2vNn1aLTyKdxTIbx4IA==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUVRoS1Q2ZDZIZDUzdlpD
            Zm9Xb2FZbGxlWVNXQ0RzalJ2eDlvT1BUSEJBCjNpdDFTVG1Zb2lheWhLdldVdnQ2
            L3p2TzdSTjFKNTBKWEdFZmhXazU3bVkKLS0tIHM3c0xYRVQ0TWpkcXArTWdlSWVL
            NXlsZ2tTbzBoKzZXeE9lenhjc3lqWVkKFcBLCTko6J0KwH/OjN2oiwQdXSXMAO3Y
            b/x7hbfcxFq5GbzixX5ap9ng0zusPdJvuZEaEMlGI58FnskXjEzkUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T06:46:27Z"
    mac: ENC[AES256_GCM,data:jTPDYnrHbxXIn/B7DY/3/xMDzbsErUrMEoBajE6M0cK5vD4Cwrxcz8PBCqVB9Niiex+TZxBvuaJ3YguJUmHw/pAs0Vd3mHdkd8Q9inEjpbaQiGGhHyCRIIIMVMSHtdJJ7zzjR2r1yhUQbfsbV01Rk2gKW1gLOj/51iZbdyp+Ke8=,iv:34DuK8S/IuiohIo9/oXVFyxsVMg/DMlt5YWA53yat2g=,tag:LRYzNbZVHOX92TdYaw4Sjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
