apiVersion: v1
kind: Secret
metadata:
    name: garage-credentials
    namespace: garage
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:TJlhQ99bPOKEIDAz,iv:keO9K6Gn7m304q2FQ3yI+3wzYKBDiEurgiyx/XXs2Nk=,tag:EEma6IsHnIwGQuHtI4d6mg==,type:str]
    secret-key: ENC[AES256_GCM,data:V0ac3VlDCR/cWd15TJCpAxGLxruU8/VDa5SJPX69+C1vqx9y4EhO+paiG83u7Ds=,iv:MW7OeSCfgRor501tgI/dtrb9tweB6Xp3Lz+W4vLzpag=,tag:CukMI3UUkXZnn298KyzqTQ==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUVRoS1Q2ZDZIZDUzdlpD
            Zm9Xb2FZbGxlWVNXQ0RzalJ2eDlvT1BUSEJBCjNpdDFTVG1Zb2lheWhLdldVdnQ2
            L3p2TzdSTjFKNTBKWEdFZmhXazU3bVkKLS0tIHM3c0xYRVQ0TWpkcXArTWdlSWVL
            NXlsZ2tTbzBoKzZXeE9lenhjc3lqWVkKFcBLCTko6J0KwH/OjN2oiwQdXSXMAO3Y
            b/x7hbfcxFq5GbzixX5ap9ng0zusPdJvuZEaEMlGI58FnskXjEzkUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T06:50:03Z"
    mac: ENC[AES256_GCM,data:ozuoJ2bEqT6+Ui3Q+GNViBRfMYvNcghSvoN6M9fmfhsBIzC5Rz/VijFi7AGDTNP8Mu7+i3bTjTSiGkOT63LChXQiB1TusbPTAzWMF1Bv0+Z4QCYNWTFx5rzQmFP4Xqy/o1tL0QihX4r3FvJL5Vh8Vlku8hi0+317bdqHCIl/G3U=,iv:Uhgklj+ZHVmoXputSGp2X9tWRUn2vB6QEp7xvqh79JE=,tag:R94r+gKnsc8wWj3gCtfENQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
