apiVersion: v1
kind: Secret
metadata:
    name: garage-credentials
    namespace: garage
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:TJlhQ99bPOKEIDAz,iv:keO9K6Gn7m304q2FQ3yI+3wzYKBDiEurgiyx/XXs2Nk=,tag:EEma6IsHnIwGQuHtI4d6mg==,type:str]
    secret-key: ENC[AES256_GCM,data:V0ac3VlDCR/cWd15TJCpAxGLxruU8/VDa5SJPX69+C1vqx9y4EhO+paiG83u7Ds=,iv:MW7OeSCfgRor501tgI/dtrb9tweB6Xp3Lz+W4vLzpag=,tag:CukMI3UUkXZnn298KyzqTQ==,type:str]
    rpc-secret: ENC[AES256_GCM,data:jlEkJJtpuD+y7Vsm3Z4K5Bg2n1AF9WEBl1hpumBGKHIsaOFocn4o/RGk403mgsut,iv:mpJJf8IjG+WoaYYF1Ub02qbyoKq7cWir8sXsKJaips4=,tag:sD548ofJBLBvB1Wqd47RKg==,type:str]
    admin-token: ENC[AES256_GCM,data:rTGkl8ITc2MHcseOOHI7HERrl/61waApD8T48r/rWRtIwvpiKl+P33p2kW4lWdus,iv:LTrpsyJ89uvnupWmHKUO/13Ek+uTdV0dTdFbB9GAIMo=,tag:2dU0ksLxEdGKOCEJbo3ONg==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUVRoS1Q2ZDZIZDUzdlpD
            Zm9Xb2FZbGxlWVNXQ0RzalJ2eDlvT1BUSEJBCjNpdDFTVG1Zb2lheWhLdldVdnQ2
            L3p2TzdSTjFKNTBKWEdFZmhXazU3bVkKLS0tIHM3c0xYRVQ0TWpkcXArTWdlSWVL
            NXlsZ2tTbzBoKzZXeE9lenhjc3lqWVkKFcBLCTko6J0KwH/OjN2oiwQdXSXMAO3Y
            b/x7hbfcxFq5GbzixX5ap9ng0zusPdJvuZEaEMlGI58FnskXjEzkUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T07:13:07Z"
    mac: ENC[AES256_GCM,data:gwWqPsdOhxAD6ZMjzGrCLrphSheVmTlUbBrcPPIHY1fDOwQ7s0h52JyX72RJW/Jlawk2dNpLD8YKbPjhYveWGR/VMujRaxRmgwOxOg3UrokALIfhuG2ytRGj0cskOABqhDx19UcPc6ywdaIVgO13SJ5/p1KtiuB6oF0XSTCUECw=,iv:jccwzcmRnKIKfOEMDIQC/Q86SGdkT0U1vbhx/Fogtqw=,tag:+wIDbTmhqCafySHA9AvXjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
