apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
  - target:
      group: source.toolkit.fluxcd.io
      kind: GitRepository
      namespace: flux-system
      name: flux-system
    patch: |-
      - op: replace
        path: /spec/interval
        value: 6h

  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      namespace: flux-system
      name: flux-system
    patch: |-
      - op: replace
        path: /spec/interval
        value: 12h
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-age
  - target:
      kind: Deployment
      name: "kustomize-controller"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=5s
