apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:dAHJ7AyOY7EPzrbOUbcQvD9AiwzLtiExJ3TB68cmY8yZ2fqAIXeZlh5hhUDbDlPsgu6/gog=,iv:IdN2YgZ/LI5DvI81Y2pOfoAPGBC5AEcdyMhoJqgJn7U=,tag:B4m8w+5j7T2ZYQdgvb8jCA==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWtLb3hqS0cyNERNTlRW
            ZnVoMXZrTzVVcDJNMC9PQVZ6MjdNYzhVTERjClZ3cGFKTGtSSC9kZWtqcTMvd0RH
            a2hwUzZEM3NWSmoyRXpaTk1Rb0ppeGsKLS0tIGkzQTdPbFZNcTdQak9RY056TkVn
            RytSRUk3YytDN0lpTWx6MHZ2L2VYSnMKPA9A38JQCMKFrc3z+v7rlhEm+23EzInd
            xpYxZigqaUqd73u4x2kDUb0FaNbYTdb/aTNZ+UtbHuIiHZFbSYmc3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T11:34:57Z"
    mac: ENC[AES256_GCM,data:px5vdT2xfGAFTseVcfMA6GOmmobP6//D4cqXfpCez+KvU7HqzdUOoYg9vUL1PwYDnIqVSULmpp6xqWiamO19ahJ1ksjtDCzhi5CjWmEG9eYG/s6DUHatL48iAVEEwdlu7i2bdUAg8tpQqb5jQZEsNPXTJM4bCCYdAm/XlHjUHk0=,iv:QgZ+MUkAU9/ikXR/z+mn7fMTsyLsfIqYmEOVHI2bgPQ=,tag:ZgnkbKf/Wu7kDBhr/QRFYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
