# infrastructure/lab/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/wallabag
  - ../base/nextcloud

secretGenerator:
  - name: nextcloud-admin
    namespace: nextcloud
    type: kubernetes.io/basic-auth
    behavior: replace
    envs:
      - nextcloud.admin.enc.env