apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: artifact-gen
spec:
  artifacts:
    - name: apps
      copy:
        - from: "@repo/apps/base/"
          to: "@artifact/apps/"
        - from: "@repo/apps/lab/"
          to: "@artifact/apps/"
        - from: "@repo/configuration/lab/"
          to: "@artifact/configuration/"
    - name: configuration
      copy:
        - from: "@repo/configuration/base/"
          to: "@artifact/configuration/"
        - from: "@repo/configuration/lab/"
          to: "@artifact/configuration/"
    - name: infrastructure
      copy:
        - from: "@repo/infrastructure/base/"
          to: "@artifact/infrastructure/"
        - from: "@repo/infrastructure/lab/"
          to: "@artifact/infrastructure/"
  sources:
    - alias: repo
      kind: GitRepository
      name: flux-system
