# infrastructure/cert-manager/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure.yaml

configMapGenerator:
  - name: init-config
    envs:
    - init-config.enc.env
