apiVersion: v1
kind: Service
metadata:
  name: flux-receiver-tailscale
  namespace: flux-system
  labels:
    app.kubernetes.io/component: notification-controller
    app.kubernetes.io/part-of: flux
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: "${cluster_name}-flux-receiver"
spec:
  loadBalancerClass: tailscale
  type: LoadBalancer
  selector:
    app: notification-controller
  ports:
    - name: http
      port: 80
      targetPort: http-webhook
      protocol: TCP