apiVersion: v1
kind: Secret
metadata:
    name: oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:0oUc9/d1uThIPb8SElJ4CLU=,iv:vIxO1JogiBDPQ0hTXSkoqC5LpzMg/yvDxEFhlpbxGXg=,tag:dgEpZOTUacVoTbcOJPVFiQ==,type:str]
    client_secret: ENC[AES256_GCM,data:X/xTfD/J5hcaGwqTSaoIfyc4+39L5Lvqyv+N23f2vU0zMG/cjmF6e1718CStoiWMggUqxWtYATiIqnxBADiQng==,iv:ZkswgfsnzWHtc7eRB15ILhb0dU1H7Tt+4Qlc/y4ALmc=,tag:3ra7kw49zASC0dRX8qd/Zw==,type:str]
sops:
    age:
        - recipient: age1u08wpcpz0a82pu639dssxehu0eanl65f0kldysjjvqh2u3mjcqlq428a87
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYnFQcURTaFlOZFAzTjlS
            Znc2V2g5OFVkaTR3cnV6MUM5ZmJmL0lUZ244CitxSzJJV3N5aEJkS2s5aERaTlJS
            L3laS3J5dWJBcTRWOFpHSGRiZkZjRkEKLS0tIFZaWEl2aVJodDZWb0ZrT2Q1S0tu
            OHI4SmFLQUdSeHVBck5EODdjZ1hLc0EKKdRSp53VjuJVyT0cui3lFBuooF3l8tqL
            zDhndzu/89fPofwsabzSi0SvQjFnRTt8aKgUzh2yXDP5Sc+mtC/u9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T12:17:13Z"
    mac: ENC[AES256_GCM,data:KPbai4l2dWoQ3X9liTxxCPP0sML5iOCjzCDqv+H5uXVKgjR0bFGSRJbxIMBCkMQHFL+iOu2fj9qg8ksl8ajUChBItm5ZgMGbn0P3UhrDd7GqAnIMMDFadPRxmdywLz2FTYTT3ntJMU8DkEAi/eqUv+wqAnI9uQe72Lg6kzByqfI=,iv:9zF75Z438Btyi/S1JxBDXzVTUsfGJZQAWNQeHdKlmVM=,tag:TM6I65imykXRuIHEOE15Cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
