# configuration/local/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - cert-manager
  - database
  - envoy
  - gateway
  - metallb
  - tailscale
  - flux-receiver.secret.sops.yaml
  - intel-device-plugins.gpu.yaml
  # - tailscale.connector.yaml
patches:
  - path: ./database/cluster.yaml