apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-recovery-pvc
  namespace: data-restorer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi