apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - flux-ssh-key.enc.yaml
  - repository.yaml

patches:
  - path: ../_flux-common.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
