apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
spec:
  cluster:
    name: postgres-shared
  name: immich
  owner: immich_user
  databaseReclaimPolicy: delete
  schemas:
    - name: public
      owner: immich_user
  extensions:
    - name: uuid-ossp
    - name: unaccent
    - name: pg_trgm
    - name: cube
    - name: earthdistance
    - name: vector
    - name: vchord