apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: immich-user
spec:
  cluster:
    name: postgres-shared
  name: immich_user

  login: true

  # Only enable superuser during restore
  # superuser: true

  databaseRoleReclaimPolicy: delete
  
  passwordSecret:
    name: immich-db-credentials
