apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
spec:
  cluster:
    name: postgres-shared
  name: immich
  owner: immich_user

  databaseReclaimPolicy: delete
  postInitSQL:
    - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
    - CREATE EXTENSION IF NOT EXISTS vector CASCADE;
    - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    - GRANT ALL ON SCHEMA public TO immich_user;