---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: memos-charts
  namespace: flux-system
spec:
  interval: 36h
  url: https://github.com/usememos/helm.git
  ref:
    branch: main