apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner-backup
  namespace: local-path-storage
spec:
  releaseName: local-path-provisioner-backup
  interval: 24h
  chart:
    spec:
      chart: local-path-provisioner
      version: ">= 0.0.35"
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
  values:
    # 必须指定不同的 provisionerName 和 configmap 名称，防止与默认的冲突！
    storageClass:
      name: local-path-backup           # 专门给备份用的 StorageClass 名称
      defaultClass: false
      provisionerName: rancher.io/local-path-backup # 必须唯一

    configmap:
      name: local-path-config-backup    # 必须唯一

    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /var/mnt/my-data-volume    # 专门指向移动硬盘挂载点