---
apiVersion: v1
kind: Namespace
metadata:
  name: paperless
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Pod
metadata:
  name: recovery-pod
  namespace: paperless
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep", "7200"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: device-path
      mountPath: /dev/sda1
    - name: target-pvc
      mountPath: /mnt/target
  volumes:
  - name: device-path
    hostPath:
      path: /dev/sda1
      type: BlockDevice
  - name: target-pvc
    persistentVolumeClaim:
      claimName: export-pvc