apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: nfs-schedule
spec:
  podConfigRef:
    name: podconfig
  backend:
    local:
      mountPath: /mnt/nfs-backup
    volumeMounts:
      - name: nfs-backup
        mountPath: /mnt/nfs-backup
        subPathExpr: $(POD_NAMESPACE)

  backup:
    # https://docs.k8up.io/k8up/references/schedule-specification.html
    schedule: "20 18 * * *"
    # schedule: "@midnight"
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 2
    # Job timeout
    activeDeadlineSeconds: 5000
  check:
    schedule: "@monthly-random"
  prune:
    schedule: "@weekly-random"
    retention:
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 6