apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-credentials
    namespace: nextcloud
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:YWqcgKVfb3grG2HSI5c=,iv:7RuIsyggrp0f9Oh9xbHMOPZepRIm3LZfHF1tkKpC+dc=,tag:5S8xie3p2vwhNSanC1Pe2w==,type:str]
    password: ENC[AES256_GCM,data:3qkZ4S7yIWBLJ6jYLTm4Kh0quymJAnPtQIbrEnuJ7dQ=,iv:KwGpNi5wISTvRGpYNQh5+H0pHB2YdyNFm8cG7CLboKQ=,tag:yHVjv5RxGIFNsa/SEEIEig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRVQxc0JIdUJPSFdPT1dq
            T2tuU1NjM29ZbTVtWEZBMzFTMFZ4NTJ5NWdjCkpVVEM0ek96ajRCZ0dSUFE1b0Zu
            RzFTRitEN05OclRLVG1wcGwrY0M3RzAKLS0tIDNsMDdjNWUyWm5aZkM4ZjVqY25E
            U0hidU1FMWoxNmdmTXcvcmI5R0tSTWsKxZhEVmEnJ8CnEZ5JLeYKDkNf9tutSNvG
            +A+c2UIlkpf7LhuqraYJ8q/L8/uDN9gt5Ao7+BZVV5pdVPQ0qszjjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T14:05:28Z"
    mac: ENC[AES256_GCM,data:oFSR2olhtTSm6u+dwMqdiRP9/hgqPmcfgi6GyI1Q4POC2B3WzV9P4/lEKPegq0EYGcUCVR6HecsLN1zC+yKMgU6/i9SIz1UD3agGfyBxzA1A562WNd/9QbEW2dB6hguTnSML8neV6OcKV6XK+hbHERJcO0Z9UkjvpkMbegi49D0=,iv:m+1S4QElr8tNVmZ5tJ6biev6Le9NSjLsLTRG2zkkMWg=,tag:aWHTv4mQAmNo74XqKLJYjQ==,type:str]
    version: 3.13.3
