---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 24h
  chart:
    spec:
      chart: nextcloud
      version: "^9.2.6"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    nextcloud:
      host: "nextcloud.${domain_name}"
      extraEnv:
        - name: OVERWRITECLIURL
          value: "https://nextcloud.${domain_name}"
        - name: OVERWRITEPROTOCOL
          value: "https"
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'setup_create_db_user' => false,
            'maintenance_window_start' => 3,
          );
      extraVolumes:
        - name: post-install-script-vol
          configMap:
            name: nextcloud-post-install-script
            defaultMode: 0755
      extraVolumeMounts:
        - name: post-install-script-vol
          mountPath: /docker-entrypoint-hooks.d/post-installation/setup.sh
          subPath: setup.sh
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      host: postgres-shared-rw.database.svc.cluster.local:5432
      type: postgresql
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db-credentials
        usernameKey: username
        passwordKey: password
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi
      nextcloudData:
        enabled: true
        storageClass: longhorn
        size: 15Gi
    httpRoute:
      enabled: true
      parentRefs:
      - name: eg-gateway
        namespace: envoy-gateway-system
        sectionName: https
      hostnames:
      - "nextcloud.${domain_name}"
    readinessProbe:
      enabled: false
    livenessProbe:
      periodSeconds: 900
    collabora:
      enabled: true
      collabora:
        server_name: "collabora.${domain_name}"
        extra_params: "--o:ssl.enable=false --o:ssl.termination=true --o:net.post_allow.host[0]=nextcloud.${domain_name} --o:storage.wopi.alias_groups[0].host=https://nextcloud.${domain_name}"
        # extra_params: "--o:ssl.enable=false --o:ssl.termination=true"
        aliasgroups:
          - host: "https://nextcloud.${domain_name}"
      route:
        enabled: true
        parentRefs:
        - name: eg-gateway
          namespace: envoy-gateway-system
          sectionName: https
        hostnames:
        - "collabora.${domain_name}"