apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qHzIpRE=,iv:dS8BNYy4ostbp0dqKqEel1E5Dqh3lSoggFJymloMzkI=,tag:629bkZyY329EJPEkXjsVmg==,type:str]
    password: ENC[AES256_GCM,data:ir+UQ/w8+f5RIQH7DdkXMWqHTB3sRSB74pSs5q5dhj0=,iv:lIo/soQwLW4tCPao2xsrjbv3xr9hTloIFUo3SDWWjDM=,tag:wkn06GcxjnFFBfT8BteY/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaUFPNzBjSnh6MFd6b0NL
            MExTYTdlUTFFR3duZXZ5MTFYbVoya0dUUWxJCkI0V284a0FTcEdCK3JEcW02anJu
            ZGx1RG14TmdBNCswZlFjRW9sVXQ2ZUkKLS0tIGhQUXB1cXlyVjJLRFF2M2JqQ01Y
            LzBUa1c2U2JPMkNDUktRSUE1YW81eEkKiTlhdYlEpSeTpUWkjFFuVYGA0cOCJEUR
            7kzHq2RqraewC1wPsIhm2WCIvkeryr0SgsZcbhgAFW56hMX3gjWW/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T14:12:45Z"
    mac: ENC[AES256_GCM,data:lXV1UL/xxiOpubqRhk1OujPObhyx3o3kq15/FmzZNK98tcX/eKO2Mfy/TJvtbQrqQT9qC7reucClQVQt9nFv7vKuS6se2+/GTXg+jykVXZLMr8lMQ5sQLbB0kUcKylPA3EAEdEcFquwRnb5l8B0zl9TFj97SDADbdXll4XFcGoI=,iv:wdmg5qefX/9PTCh3AMqEusJrbaujF7hH6EfGD/dCt00=,tag:YkyFmyWFNNWGA/zE+pb5cw==,type:str]
    version: 3.13.3
