---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: litellm
    namespace: flux-system
  values:
    image:
      tag: "1.84.0"
    db:
      useExisting: true
      endpoint: litellm-database-rw
      secret:
        name: litellm-database
        usernameKey: username
        passwordKey: password
    environmentSecrets:
      - litellm-env
    general_settings:
      master_key: os.environ/PROXY_MASTER_KEY
    proxy_config:
      credential_list:
        - credential_name: default_gemini_credential
          credential_values:
            api_key: os.environ/GEMINI_API_KEY
            api_base: https://generativelanguage.googleapis.com/v1beta
          credential_info:
            description: "gemini gree tier"
            custom_llm_provider: "gemini"
      model_list:
        - model_name: gemini
          litellm_params:
            model: gemini/gemini-3-flash-preview
            litellm_credential_name: default_gemini_credential
            rpm: 5
            tpm: 250000
        - model_name: gemini
          litellm_params:
            model: gemini/gemini-3.1-flash-lite
            litellm_credential_name: default_gemini_credential
            rpm: 15
            tpm: 250000
        - model_name: gemini
          litellm_params:
            model: gemini/gemma-4-31b-it
            litellm_credential_name: default_gemini_credential
            rpm: 15
        - model_name: gemini
          litellm_params:
            model: gemini/gemma-4-26b-a4b-it
            litellm_credential_name: default_gemini_credential
            rpm: 15
