apiVersion: v1
kind: Secret
metadata:
    name: litellm-database
    namespace: litellm
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:881uFYocqA==,iv:zmBH4WWRpYINh/BMS2Zz+7N50nptILDqzYnlTnthhPk=,tag:F6cM8J5BB2LWmr3oMCNxvw==,type:str]
    password: ENC[AES256_GCM,data:H5cMBBSV61OpvODIMV6f8/7BqWd3Gt+9Ni6Kt/2c,iv:wpp1byOK1C6KWCYQR3y+7o1HZJyaQ/glXF4pzN2cNmw=,tag:dLW8oCUTeJsNnhknq+KQ5A==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRVQxc0JIdUJPSFdPT1dq
            T2tuU1NjM29ZbTVtWEZBMzFTMFZ4NTJ5NWdjCkpVVEM0ek96ajRCZ0dSUFE1b0Zu
            RzFTRitEN05OclRLVG1wcGwrY0M3RzAKLS0tIDNsMDdjNWUyWm5aZkM4ZjVqY25E
            U0hidU1FMWoxNmdmTXcvcmI5R0tSTWsKxZhEVmEnJ8CnEZ5JLeYKDkNf9tutSNvG
            +A+c2UIlkpf7LhuqraYJ8q/L8/uDN9gt5Ao7+BZVV5pdVPQ0qszjjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T20:45:51Z"
    mac: ENC[AES256_GCM,data:ozxyKfrHfCoCzkyz2Tn7qocM+W0XUrop4UK1OvSlGxXDRWj/Dc2JAx7bqaaCREaTpaNDl0DmLZLJqqX3+tFZkisfIP2uECz7xXf3ia6ZXyDAdfNerBAcKoO2ATlsVm5c3VUjCyt20JTXovdARBJ4U6ZEasADIfPl7+2iuJ6dUbU=,iv:Dqy3B5HCMwMLCkFmeEhqSbKeBy5160iAZDmg5NuFJ1k=,tag:EyywE9A5hiqUC+LiTo3wkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
