apiVersion: v1
kind: Secret
metadata:
    name: llm-api-keys
    namespace: litellm
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:QFp+pFpVRnuzheQvoXZFHR+5TsO86BNivVgYLaU0,iv:zD7fx4nyJv3nS66V1C8VTg1iuXCehcjhShQlEBoNZAs=,tag:2oqaWsZ5bmTNkoM3OZ/0xQ==,type:str]
    gemini: ENC[AES256_GCM,data:l4jh58fjABIdZGcHb65hhXfrQOLK1T617DySb5IEL1tBIcINqeE9,iv:WUMmz3h7Ef9KAg/5EAJ4CuI7F/wbbdMx3fmfAzf8On0=,tag:xRik+cNqBPrydAYU5HM3OA==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcHE0bnI2S2ZyRVdjTEtN
            NElrOHlGOHRDaXV1d0s3ZDBEWEJRMU5IUjE0CktZRHRVdWlYRUtyeHdjLzNqTWFW
            MlVFVnlGbFRZeGFpZDZZZm92cHlxRXMKLS0tIEEyaGZob2xRdU9SaXZKRDY5YjJJ
            SDZmYytDNmtwV0RSLzNuQ3hIZ0RESzQKuidLQ8GhhyIt0yyvkNQqAReLeFHb5oUv
            9ARZOl1JOfIDl3zGRy5sjWWv5psHp82PTPwuV7knPvWEvjeYeCxlaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T18:31:30Z"
    mac: ENC[AES256_GCM,data:9ftlqJhI18twh1ImFJDLqiFxrWYTvFP9rbjBVDtzPSxG6JcyiLspJAzIzR4pHoy991T2cPFPDo1fLSpv+d1r9y3k8fghYxWSIiYcjNHxncPg3XApf+agpiwGFAZANd+wXH3hZmIfJdeiHMtCS8pUah9y0HcDO094qAUyaZpsDMA=,iv:O01VPdmP8lMEFUUrwGdkIkpz0pdUxqRx4LKoXpYBn38=,tag:GMouwC8TgHl4tolxuZf8UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
