apiVersion: v1
kind: Secret
metadata:
    name: oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:IvB6CJYTgCPMFmx7L5PURt4=,iv:BXpvyzRo0rOpHilhmV54c6IfMcALW4n+YNXVjdPohno=,tag:AN6ftbjaNsMgpkjVtHqtIw==,type:str]
    client_secret: ENC[AES256_GCM,data:nNwLbOUSJuhUJOdbuSAbAkkn0vCH6oEgIwExtHUl08YQGrTSR+UoJLxPJrJ+y7CEAQFk0THvKrlWUjO+W+F/5w==,iv:h8uUtG6rw/1MCWK35WCWAw2c78ue5OLKrubw/4HuVOg=,tag:i+mhCJFnf/m7m3dLT/OLqw==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNXRHTkRuS3F4a0Q1M1pH
            OFc4Q1huc281SVB4bHlpMjJQdktONlp5ZVRVClE0MnpwMk96V25XWTBsb0ZjM3Nh
            dldISzc4bnFKRkZHb3JYVEJ5VnNnOXcKLS0tIFN3VkNNZFBvODJLaFR4cG5EWHdt
            djVYMXVDbVBVeDhEblRXZnBYa0h0Rm8KzsF5F/dyrytlnDyuVf2C5ZKMDmnyoUg7
            y/i4tFhH2PC4rII2EFQ3sxv9OF9Z6Umr1o0eBXlby2RXNaSk6rZYdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T12:56:40Z"
    mac: ENC[AES256_GCM,data:JS+04vmceJMwSTQbNeCm7jGbgDQpfVQkh56Ufegp8FTSuIIGTzYyi92KwtjrJ35ML7UZeCqXfH3/rG0sbnA5Y/nnBhD0BH4WqbB0go48blY7BokBp8v0XGjufwoWr+RijCFabqyWtg1kQJQq59Sb/CcnK9rHRraYluP1rIheb/M=,iv:UBmhtNpXgTRVlDg2QjHwi1giCL5DsAIIHxoFsIkqRa4=,tag:naRvXCIwDBqbjAVXUYzuPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
