apiVersion: v1
kind: Service
metadata:
  name: coder-service
  namespace: coder
  annotations:
    tailscale.com/tailnet-fqdn: "coder-coder.${tailscale_domain_name}"
    tailscale.com/proxy-group: "egress-proxies"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
  - port: 80
    targetPort: 80