apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: immich-user
  namespace: database
spec:
  cluster:
    name: postgres-shared
  name: immich_user

  login: true
  superuser: true
  createdb: true
  databaseRoleReclaimPolicy: delete
  
  passwordSecret:
    name: immich-db-credentials
