# configuration/local/database
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich-database.yaml
  - immich-role.yaml
  - immich-secret.sops.yaml
  - nextcloud-database.yaml
  - nextcloud-role.yaml
  - nextcloud-secret.sops.yaml