apiVersion: v1
kind: Secret
metadata:
    name: memos-db-credentials
    namespace: database
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: memos
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:9vXoZ3E/c03aUA==,iv:q5A8Q7IsSKjcValtCaENoAAaOdAlcvSWuCV0S4nzYmI=,tag:7v44s+Ohebmvxi6/Nb3TAQ==,type:str]
    password: ENC[AES256_GCM,data:kxY40rJ2imubgrByHnEQeXcVSDFKS4jdLTp3lTrdgI8=,iv:j94BkgXEmH+ujT2eZLehMncqc9wA4Pdcu0kxRoQpWHE=,tag:vWQp/nN2d+cbzUDIIVntrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMUdJZWIyTjQ5WWxkTTJU
            cm9ZQWg2ekFzY0d1UUJoYXNTY2FPb3J3QnhBCjBlTmdOY1VNbE4wSVBIM002Qmk3
            bVJlQ3dXRjhxNWpPdyszbXQ2VSs3VEUKLS0tIFEvcGVmczJZS3VaSmxFb0tTMEZN
            S1dZM29HbFoyQmpFbWVPQlFxZ3VOeWsKHBUdZGprF0yrj9fg1jLqpC9g765fX6Yr
            bAWPk9MB0xT0981nB+ARNEipOnXnGrC8cWfc5gn5zbcR7//4Hk/Vmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T13:28:06Z"
    mac: ENC[AES256_GCM,data:d13+gcQclyo6Pv4P1KSkKSBXYKkyVzjZLFwqpOrW0UDeOuaAbM11PldiU8nybVgnBugW/azZeNHPjIzMrI04mO2Ps5zco8I1A4JllxVz24g8s2hFpbK/kGK6+71tgTTa+W7LOnb0VDrCxGpVzkCZV09urZL9NiZPVaGb0jS+GI8=,iv:19bs4t5eRzy1P5VhAFkPeQPXZvlIP5cvKn2HImeHbFU=,tag:G7w6ZeGQ91oaP/ijMRR/XA==,type:str]
    version: 3.13.3
