apiVersion: v1
kind: Secret
metadata:
    name: immich-db-credentials
    namespace: immich
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:2sJTeDKBIEhVu6E=,iv:/GCjN9wLLmzqtb+hGF/FVCLPfX1uiQ4uMxU2eJce5Qg=,tag:KF2CBoJzRGwdkEjsCChbvw==,type:str]
    password: ENC[AES256_GCM,data:h//hjpeT60KQu+YaVQLkR0F47O3KNzk1eoQZU6Eb,iv:l4USgPEKpKCeb2xDyvViuHTqf6B9kZETnaK1pcRYxSg=,tag:c8B+sURP2tQlfRfqS/50qQ==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRVQxc0JIdUJPSFdPT1dq
            T2tuU1NjM29ZbTVtWEZBMzFTMFZ4NTJ5NWdjCkpVVEM0ek96ajRCZ0dSUFE1b0Zu
            RzFTRitEN05OclRLVG1wcGwrY0M3RzAKLS0tIDNsMDdjNWUyWm5aZkM4ZjVqY25E
            U0hidU1FMWoxNmdmTXcvcmI5R0tSTWsKxZhEVmEnJ8CnEZ5JLeYKDkNf9tutSNvG
            +A+c2UIlkpf7LhuqraYJ8q/L8/uDN9gt5Ao7+BZVV5pdVPQ0qszjjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T16:31:29Z"
    mac: ENC[AES256_GCM,data:tj0dfW4bIZJucXQVKzlIS1ZqXCrVpIzpppgeUtbducgB1jZNIlqQJZG7kHtQm7uE5TJ0CCsu7qMX2ODGglQSyVOpmi5taNdv0dFcM3D3IzR6Zwzqq6pDDQ2lisNJVFG+qewi3NFoBVu/mkFk976qrLr84yKk1NI0UBfpDCeRrcM=,iv:BvIYM5fyUq1HswBLt32THgnkWXYH5kaqOxZll82bwA4=,tag:Khx2dVP/c6qss61G6VfHgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
