apiVersion: v1
kind: Secret
metadata:
    name: immich-db-credentials
    namespace: immich
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2sJTeDKBIEhVu6E=,iv:/GCjN9wLLmzqtb+hGF/FVCLPfX1uiQ4uMxU2eJce5Qg=,tag:KF2CBoJzRGwdkEjsCChbvw==,type:str]
    password: ENC[AES256_GCM,data:h//hjpeT60KQu+YaVQLkR0F47O3KNzk1eoQZU6Eb,iv:l4USgPEKpKCeb2xDyvViuHTqf6B9kZETnaK1pcRYxSg=,tag:c8B+sURP2tQlfRfqS/50qQ==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRVQxc0JIdUJPSFdPT1dq
            T2tuU1NjM29ZbTVtWEZBMzFTMFZ4NTJ5NWdjCkpVVEM0ek96ajRCZ0dSUFE1b0Zu
            RzFTRitEN05OclRLVG1wcGwrY0M3RzAKLS0tIDNsMDdjNWUyWm5aZkM4ZjVqY25E
            U0hidU1FMWoxNmdmTXcvcmI5R0tSTWsKxZhEVmEnJ8CnEZ5JLeYKDkNf9tutSNvG
            +A+c2UIlkpf7LhuqraYJ8q/L8/uDN9gt5Ao7+BZVV5pdVPQ0qszjjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T07:48:17Z"
    mac: ENC[AES256_GCM,data:Q1gNdA1LXYsFHECs4YcJD+XO0gC66Q1vReIHcNpJfFfRZhEXvFrA0ue9xwGpvKrtYCNIt6GBQzRrnekS+VkE0B2owTCQiIdeLljpKduW0OhMZFf5HqHy3BQItRJeryar0fEV8eJcm6g3L65903hbj1dLrlcbzVn+vG+TfIdJiwk=,iv:Q2bXq747jbZJ2wc4g0+uEaa/NCfMvtV7PugRs63qMkM=,tag:KepYzaZe9fIi0LLoKV3vBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
