apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg.yaml
  - namespace.yaml
  - pvc.yaml
  - release.yaml
  - repository.yaml
  - route.yaml
  - secret.sops.yaml
