apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-queue-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi