---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: immich-charts
    namespace: flux-system
  values:
    immich:
      persistence:
        library:
          existingClaim: immich-server-pvc
    server:
      controllers:
        main:
          containers:
            main:
              annotations: 
                backup.velero.io/backup-volumes: "data"
              resources:
                requests:
                  memory: 256Mi
                  cpu: 100m
                limits:
                  gpu.intel.com/i915: 1
                  memory: 3Gi
                  cpu: 2000m
              env:
                TZ: Europe/Berlin
                DB_HOSTNAME: postgres-shared-rw.database.svc.cluster.local
                DB_DATABASE_NAME: immich
                DB_USERNAME:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db-credentials
                      key: username
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db-credentials
                      key: password
              image:
                tag: v3.1.0
    machine-learning:
      controllers:
        main:
          containers:
            main:
              resources:
                requests:
                  memory: 256Mi
                  cpu: 100m
                limits:
                  gpu.intel.com/i915: 1
                  memory: 3Gi
                  cpu: 2000m
              image:
                tag: v3.1.0-openvino
      persistence:
        cache:
          enabled: true
          size: 10Gi
    valkey:
      enabled: true