apiVersion: v1
kind: Secret
metadata:
    name: immich-database-app
    namespace: immich
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:DvsrzfmlTA==,iv:CTSEFUbhrPzJN3GlRAG9fV5gAjSa1Fefo8VlcPbx7O8=,tag:DNapoEOlvWdWARGGJfy19A==,type:str]
    username: ENC[AES256_GCM,data:fgSB,iv:5Z+RgO7P6Y0aYGQfitRyfE8ESnBlgvPwBLdNq+FRC1w=,tag:NdR+HiI8cao8/ycy4BJP3Q==,type:str]
    password: ENC[AES256_GCM,data:wpASY1GMAVvfEQqsR32m/sBVYlcmOnoLSPj6XrUN,iv:SkJpc9Qc5dEycFo/vBJBUqfb1PeXNvovfvJ54VIaBNw=,tag:zxeQ+mVuf+XDi58uhF7HcA==,type:str]
    dbname: ENC[AES256_GCM,data:f/Bu5i5k,iv:7Oz2Lyu36d4ckTHOHF7mS0T3bGnh+b/Y7ukVTTfky0Y=,tag:tg5vbmiNLbqOGeyCTbq2qQ==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRVQxc0JIdUJPSFdPT1dq
            T2tuU1NjM29ZbTVtWEZBMzFTMFZ4NTJ5NWdjCkpVVEM0ek96ajRCZ0dSUFE1b0Zu
            RzFTRitEN05OclRLVG1wcGwrY0M3RzAKLS0tIDNsMDdjNWUyWm5aZkM4ZjVqY25E
            U0hidU1FMWoxNmdmTXcvcmI5R0tSTWsKxZhEVmEnJ8CnEZ5JLeYKDkNf9tutSNvG
            +A+c2UIlkpf7LhuqraYJ8q/L8/uDN9gt5Ao7+BZVV5pdVPQ0qszjjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T08:52:23Z"
    mac: ENC[AES256_GCM,data:Z4L0Ex6XsH4dUJpdm7Sk+OoJkfVC8gYW6FOODZCA74ZqlMjc1w7XxPiKYhi1vaj35g0aW8GGUHYFhHkPUXI6GJ/PXI2QPjUn0vuDOthumoUK3svSRSvojyyhislH+fF83TvcAwmiH914L6EtZQCf3S5D7KTbDrD+yI+hdcf7kMM=,iv:IPDuk3Ipcm0cLD9g2vsZWSvuKvuKNVhYZCTfNhxbE5M=,tag:KWv2jhTo1Q5ko20aBi6WAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
