apiVersion: v1
kind: Secret
metadata:
    name: immich-database-app
    namespace: immich
type: Opaque
stringData:
    db_password: ENC[AES256_GCM,data:158wsqc47KGHP9PKdpe5Y47bE1S/xzkssNvl1uFx,iv:KdugsybCa9h/LabiAJMgLQ7fp9z/oTgML5drhiyN3BU=,tag:prJ6U6cM6xGM0C01jpd9Gw==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRVQxc0JIdUJPSFdPT1dq
            T2tuU1NjM29ZbTVtWEZBMzFTMFZ4NTJ5NWdjCkpVVEM0ek96ajRCZ0dSUFE1b0Zu
            RzFTRitEN05OclRLVG1wcGwrY0M3RzAKLS0tIDNsMDdjNWUyWm5aZkM4ZjVqY25E
            U0hidU1FMWoxNmdmTXcvcmI5R0tSTWsKxZhEVmEnJ8CnEZ5JLeYKDkNf9tutSNvG
            +A+c2UIlkpf7LhuqraYJ8q/L8/uDN9gt5Ao7+BZVV5pdVPQ0qszjjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T09:14:06Z"
    mac: ENC[AES256_GCM,data:+vE6n1nFhG/N4kegakG+IE/WW5QA5RIW8MmkJdt05/QpRGojVGyTzu8DgdOOW5Q27OkIBu3ER5lnHauFLJwsTlsGh0SjRv3BDeYWNVbmMC4NHwg95ZNzxw+028jqQ0VQn6gXXhHv22yNx6rdypLa+b2AomMdJkKvZ7luX6qWv9Q=,iv:dxO1Y++lX65e1mSmlCcfwYslI153K6c6fjRwBd+xnro=,tag:VXn4tB0wvUyTbAYQ5uzSkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
