apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - pvc-consume.yaml
  - pvc-data.yaml
  - pvc-export.yaml
  - pvc-media.yaml
  - route.yaml
  - service.yaml
