apiVersion: v1
kind: Secret
metadata:
    name: secretkey
    namespace: paperless
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:eDTRr7LMldOgTjSuJWhMntAbN9et/OpdksqyRldP0ak=,iv:oteVAYznAaKkb/Yl/ajE5X/TgWD63sKvCrsHrSSWsrI=,tag:zF8SWqyBOfeIsvop+LMenQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVGVCNDRqMUprWXRrY1I3
            Z0FBWDVObGF2VFJ3ZmJzSy92elBkeG5waTNNCmJPWUUzMEhleGhUZVFETkNld3R0
            YUFmbGF4VldvKy9CakRzMDAwUFVyMW8KLS0tIFhDOG8zeGEzUXdPOG9BaVNEcyth
            bUhHWWdTdzVpS2luUGMyNE5KYmFDYncK+D1mGc1T6dTLk0voFSHRp+szwXywjgE1
            n35EpvPqdmAtOp0RoZ6wKjj4cZ/41J2rg9tEgWS71LsxIsL00zhuoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T20:29:18Z"
    mac: ENC[AES256_GCM,data:IaFYZlO1GaFQ7VIY4OwG6AFQqGR+A6qDGaqby2ogugCaTaBUpm25Hj7D+zBIc4jY4nYxn+iSLywciWRzUfw94Ew8V1chZgXpPGjnz8YQLCRWrDVvmXc9jsJD+VktWBv26g8DiuE2EDg4pl9IbGLDBBOEyuN+uJBknL7aClLtjHY=,iv:Cc6FNdOlv7b7BlVu8aCqk38qTGxqBfWSs38eTYCKGJI=,tag:2sgoiZxtZsErxN8D/jGpgw==,type:str]
    version: 3.13.3
