apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloudnative-pg
  - intel-device-plugins
  - k8up
  - local-path-provisioner
  - reflector
  - tailscale

secretGenerator:
  - name: helm-release-values
    namespace: k8up
    behavior: replace
    files:
      - values.yaml=../lab/k8up.values.enc.yaml