apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 36h
  url: oci://registry-1.docker.io/bitnamicharts/minio
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "1.x"