apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: minio
type: Opaque
stringData:
    rootUser: BXpvyzRo0rOpHilhmV54c6IfMcALW
    rootPassword: NwLbOUSJuhUJOdbuSAbAkkn0vCH6oEgIwExtHUl08YQGrTSR