apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: minio
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:6ZIjQaNocMJuEDI=,iv:LB5AedxyTU/V+ixRVTKz1zvCflsA/tlRMHUsVlk48Zs=,tag:Asvb2W+NzxBrOjJthcOi5A==,type:str]
    rootPassword: ENC[AES256_GCM,data:zRwFqGei+BjbadCsSoqIuhFbsjn36UdkqlobwmDllFGjgi06O4wv9XVX/Mpsi1DY,iv:IZdXAUkJZwRm8l5zxDwJdbuIUSqM0L6xzoNVOE7ZCnI=,tag:sif2vNn1aLTyKdxTIbx4IA==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUVRoS1Q2ZDZIZDUzdlpD
            Zm9Xb2FZbGxlWVNXQ0RzalJ2eDlvT1BUSEJBCjNpdDFTVG1Zb2lheWhLdldVdnQ2
            L3p2TzdSTjFKNTBKWEdFZmhXazU3bVkKLS0tIHM3c0xYRVQ0TWpkcXArTWdlSWVL
            NXlsZ2tTbzBoKzZXeE9lenhjc3lqWVkKFcBLCTko6J0KwH/OjN2oiwQdXSXMAO3Y
            b/x7hbfcxFq5GbzixX5ap9ng0zusPdJvuZEaEMlGI58FnskXjEzkUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T06:03:59Z"
    mac: ENC[AES256_GCM,data:1gw08mcF6GlakvfJew9lkIgt7xGGkpveFSAht0+2GwpRlGlU1k+45j4lyrr87YQ7vexGbQimIcm4F+47xREQZuUgo4IQxWLxhQdcMM84TelKr7avx0HJXrbz341fzx5JLK5mRH4o2hqSP6m3Ue9+FNJcG5LITfRJBJ7fyKbzaus=,iv:oSXsr54onY0g4mFlLGHNaTpsVXpZoqT8Lzpj3OAYtmk=,tag:YxNp7qHJOKy1QufwDUaJBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
