apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-shared
  namespace: database
spec:
  instances: 1
  storage:
    size: 15Gi
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.13-1.1.1
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
  enableSuperuserAccess: true