apiVersion: v1
kind: Secret
metadata:
    name: receiver-token
    namespace: flux-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ffYndTwqAXBRQtWuKc6fHmyVe5H3myjn5XxKU1ELKs6huqsvTDqO7iCl9nIk+pj4UolEYGalMK5tHpE=,iv:sKgMAQJtfll/1Z1AD6dlSyxXFEC1nRffS1TDTyRV12Y=,tag:BzxViNECmA4nfy73nIC9qQ==,type:comment]
    token: ENC[AES256_GCM,data:zVdd5uP3mIp4u0D50+zqBx6zyj14ZAlr7BmEM89JU6pIaps4thH6rg==,iv:mGBIe+hAzaR31fvRuMxNfbpS7J+1i1vbYDymQ1VqJ6k=,tag:cJ2MBmiiiEpbFC0m8cMf+g==,type:str]
sops:
    age:
        - recipient: age1u08wpcpz0a82pu639dssxehu0eanl65f0kldysjjvqh2u3mjcqlq428a87
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdmoxbnYxRm9IV2twUTJw
            bHFtV3VKbXZLdTJpSFA1amM0OVdUVStjVHdZClF6WCt0bXNSOE9VUVdobWFnOUcr
            L1VrNDhVM2cxbTNsRVNQR1duMUc4OWcKLS0tIHloTVZUZHcxZ0FuSkpaQXd3Rjh6
            bXo3OHJVMzUvSFI2ZU5mT2ZEdGVyQTgKcvIzigkFYcXjbJneG/OZoXoBOTIY9aMZ
            eNMxQQUC8HovfMYAzj1Zj04mtFHASTKY5/mtP6zc5JUIWnhxZLkUnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T14:20:40Z"
    mac: ENC[AES256_GCM,data:iumkDF+sPRUBCb2d+FutoLtz15dALZi5UVg8Lncx1wPcZhEApdJ3cK8M21jPgKmnrJKQJjzYCfC2P2Sqs3F57j+WKDXySthmBDtIjvDRGfa6qwMGaj8QhnZ9kgRY0NHuF0cg73EpCuF3b/IyBiJ8di6OT18+CgDTe5oR3/ROZRY=,iv:7Go1vD6T4dcDr92v0gBQ3oF96BB7IyRuX91QoeiRxCo=,tag:fgOjFI4wI2SzPTL7kA5kYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2