---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: adguard
  namespace: flux-system
spec:
  interval: 36h
  url: oci://ghcr.io/helmforgedev/helm/adguard-home
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "1.x"