# app-namespaces.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: adguard
automountServiceAccountToken: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-services
automountServiceAccountToken: false