# app-namespaces.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: adguard
automountServiceAccountToken: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-services