apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloudnative-pg
  - envoy
  - intel-device-plugins
  - local-path-provisioner
  - metallb
  # - postgresql
