---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 36h
  url: https://charts.containeroo.ch
ref:
  semver: "0.0.35"
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
