---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets-repository
  namespace: flux-system
spec:
  interval: 3m
  url: https://github.com/23hp/immutable-gate-secret.git
  ref:
    branch: main