---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 36h
  url: oci://ghcr.io/traefik/helm/traefik
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "39.x"
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: flux-system
  dependsOn:
    - name: metallb
      namespace: metallb-system
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.20.4
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        redirectTo: websecure
      websecure:
        middlewares:
          - traefik-secure-headers@kubernetescrd
