apiVersion: v1
kind: Secret
metadata:
    name: receiver-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:kj/4oiM9NlHIj0NmU3q4EIGYnbu3xViBXBxrmXYaWUpqdejYYRDt+w==,iv:93DTj7H23dW4jeEErshnGv/lU5OAAXfTHqcmAwwZdjM=,tag:EjolRldRPhBsPIGLv6tp7g==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVmEwTGp6VUNGd0pFS2hp
            TmJhN2lpcEpnVDhhT1kzMDFhVFFpb09pL1FBClFvVzNySGtRdHhNY0hUbisvakR6
            Q0w0SHZYMUk0YlBFUTVCbm9TRkZwcUUKLS0tIHlCYVU2ZWxReHFOODZUTEM0Ymhl
            SVBjSWErTHZZL1dta1FHZzNGOUcyUXcKfHkd0ccB5FoAlZnr9seIjyxbbWga9QCc
            cqI5iJSW5C3u0qBOgJLiwAdMtW5hTrdXM4PURlYC6ktVeC4L6B+xmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-01T13:10:23Z"
    mac: ENC[AES256_GCM,data:dZxmkAQAmUALPyHR14t6KQIEwXOT2Ug0qX8FTOg4xHDaX2b1vBFYn26DuE7BQbd4ts/d8pL3o0ShEy2OhLFBt8MHj8zrp6SOyjGXKIyAwTzAsVn1M/cvtibKwATh5SwGmTy+kNd8kz/cXMvKMY5bSiDYtpRCiTND4IrUbOZHd58=,iv:DP1XemRRskREaRpmBfpZHOpFijradaYQqdFCn2rTqUE=,tag:uXUwntHyxiworl3QdKMgCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
