---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallabag
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: wallabag
  valuesFrom:
    - kind: ConfigMap
      name: helm-release-values