---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-gateway
  namespace: envoy-gateway-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.20.4"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.${root_domain}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-tls-secret
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-https-redirect
  namespace: envoy-gateway-system
spec:
  parentRefs:
    - name: eg-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: global-secure-headers
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg-gateway
  customResponseHeaders:
    - name: Strict-Transport-Security
      value: "max-age=63072000; includeSubDomains; preload"
    - name: X-Frame-Options
      value: "DENY"
    - name: X-Content-Type-Options
      value: "nosniff"
    - name: Referrer-Policy
      value: "same-origin"