apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec:
  postBuild:
    substituteFrom:
      - kind: Secret
        name: domain-name
resources:
  - ip-config.yaml
  - local-path-release.yaml
  - tls-certs.yaml
