apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
spec:
  postBuild:
    substituteFrom:
      - kind: Secret
        name: domain-name
resources:
  - ip-config.yaml
  - local-path-release.yaml
  - tls-certs.yaml
