---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  releaseName: local-path-provisioner
  interval: 24h
  chartRef:
    kind: HelmRepository
    name: local-path-provisioner
    namespace: flux-system
  values:
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NEW_NODES
        paths: ["/var/mnt/local-data"]
    storageClass:
      name: local-path
      defaultClass: true