apiVersion: v1
data:
    root_domain: ENC[AES256_GCM,data:flnGQVH0cFQUk1oRHl0uNA==,iv:sPVWawRE8PDmUDK54zY6oEaN/pade5I0GYMPzIJ3/M8=,tag:wdm+OeDW8IeMffQZpKJ/sg==,type:str]
kind: Secret
metadata:
    name: domain-name
    namespace: flux-system
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNk9pVnNqRWFTL2pDRWIz
            M1NXVUVOTXZlczF6T3dwL0Y3U1VXdjhLQmdvCnl0eC9KRENwYXh4OVNMTGtZM3Ur
            bEg0eW1GNkx5OUgrUGRjVE1ndGlxaEUKLS0tIG00bUxNbjZ6TzZOS09hSDZoS21S
            S2pBVm1pWGtSY3dPQk9UY2xHeldEZW8KQrtvV/1pn/AVOYwMJ2A1L1tXvdgyNd3s
            5NcMaF53eVNbc/kMpVv6hO+GudhTXkY0q1VdrM8NqZQt3RgzhYn27A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T10:11:15Z"
    mac: ENC[AES256_GCM,data:p+vb3n++aMfjzYQiEGjbsc20YVCSxEE2cd0Sf7cAmAVTIuZ71FRNeBLSPn/FxEbvusHJejEtKeFxgRZh8o805mn1I4C9MyuPU50GAmuqH50wJSP9mvxzKE6ytuuLwtkCXMuNPeb1lPAHdRKMFEcm584p9n9oeFVyjV/VOWz3H/g=,iv:IXGtSmEaVx2bRLz8DyWiSv7bv5BsyIUPikXWUrgpHns=,tag:5TxJyQQa55v18zn4MAgF0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
