apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: wallabag-user
  namespace: database
spec:
  cluster:
    name: postgres-shared
  name: wallabag_user

  login: true
  superuser: false
  createdb: true
  databaseRoleReclaimPolicy: delete
  
  passwordSecret:
    name: wallabag-db-credentials

  nodeTemplate:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "wallabag"