apiVersion: postgresql.cnpg.io/v1
kind: User
metadata:
  name: wallabag-user
  namespace: wallabag
spec:
  cluster:
    name: postgres-shared
    namespace: database
  name: wallabag_user
  secretName: wallabag-db-credentials