apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: wallabag-user
  namespace: database
spec:
  cluster:
    name: postgres-shared
  name: wallabag_user

  login: true
  superuser: false
  createdb: true
  databaseRoleReclaimPolicy: retain
  
  passwordSecret:
    name: wallabag-db-credentials
