apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: wallabag-db
  namespace: wallabag
spec:
  cluster:
    name: postgres-shared
    namespace: database
  name: wallabag
  owner: wallabag_user