---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallabag
  namespace: wallabag
spec:
  interval: 24h
  install:
    strategy:
      name: RetryOnFailure
  upgrade:
    strategy:
      name: RetryOnFailure
  chartRef:
    kind: OCIRepository
    name: wallabag
    namespace: flux-system
  values:
    wallabag:
      extraEnv:
        - name: "SYMFONY__ENV__DOMAIN_NAME"
          value: "https://wallabag.${domain_name}"
        - name: "SYMFONY__ENV__DATABASE_DRIVER"
          value: "pdo_pgsql"
        - name: "SYMFONY__ENV__DATABASE_HOST"
          value: "postgres-shared-rw.database.svc.cluster.local"
        - name: "SYMFONY__ENV__DATABASE_PORT"
          value: "5432"
        - name: "SYMFONY__ENV__DATABASE_NAME"
          value: "wallabag"
        - name: "SYMFONY__ENV__DATABASE_USER"
          value: "wallabag_app_user"
        - name: "SYMFONY__ENV__DATABASE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-password
        - name: "POSTGRES_USER"
          valueFrom:
            secretKeyRef:
              name: wallabag-db-credentials
              key: username
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: wallabag-db-credentials
              key: password
    postgresql:
      enabled: false