---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wallabag-web
  namespace: wallabag
spec:
  parentRefs:
  - name: eg-gateway
    namespace: envoy-gateway-system
    sectionName: https
  hostnames:
  - "wallabag.${domain_name}"
  rules:
  - backendRefs:
    - name: wallabag-wallabag
      port: 80