apiVersion: v1
kind: Secret
metadata:
    name: symfony-secret
    namespace: wallabag
type: Opaque
stringData:
    symfony-secret: ENC[AES256_GCM,data:/SqUd9PZZ7pyTw1Jc+Rt5wV3/vy3MuAWoIxNaiyWImzdJz6J6aAIlSVPhypg9LNz,iv:7ZLm43aFe8NUIITkcTMhfxjHLbVmcl+/94sj9F7yXKE=,tag:Ef0Rxpo2Cv7cRw1tqsJwgQ==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUnM3V2lYeklEci95Z1U2
            eEE2bWJDMWpIZVBSVUVvTUZHYWdxQWdRZ1dRCjEwN0FoNU5uQVFPdk5pZEhLUS9P
            dUpRSVF6YnRTRkZBSWFmMzhpWXNTRzgKLS0tIHhvWTB1T1pYNDc1R3RQblVUL3kz
            enQyVmZEUFdCUlNURkoySkp2NFRwYW8KHNCzxhBTmLbvOFKYAT95MjNGuGu2Qno/
            78CJTLnjGZC0pmzNnKG1hvPXB6BCVcFDORaRAN0mstyDYIY09OGy+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T08:13:14Z"
    mac: ENC[AES256_GCM,data:VoqzpkW9dwfzL7gLLz7OJ2NyoHyzQ5m/vpYqLajFHuV3+bpWssjr6TFnIIwP4XSFX7mQfxqVTwFKpCULyrV2vO7/oPsf9Gi2NuqLEayF/xgRlUsurnM1FHP4f9B97lK3BfMkzngCQKXKUFO2kWTiK3eTJarHM3a4xFpcO2hfgfU=,iv:XS60fYdz/xfn2j+AP6VDR1YG6dF2NDnvuRdeRXKlvKE=,tag:xzW8uTMsxG3+oJzzJYMvUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
