apiVersion: v1
kind: Secret
metadata:
    name: wallabag-db-credentials
    namespace: wallabag
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:C5+DuMVJ5W73RGSb4A==,iv:6PTREbjtyU1pYVX8YhjuT3bHfejlbLX0K6CN/qRZ664=,tag:3hwIZxz1F9ygebd7SNxs0Q==,type:str]
    password: ENC[AES256_GCM,data:rLeORVFYIAKmu9m1rk7vtZ2fUdd6PZsFXBx8NUr+,iv:F/fjlyDnOg+a/fT7JTMlJZ62/oRWF8AiqJdOUBWjiDo=,tag:yC3AcTBHYHDgUpHzYe477g==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UGpBQjQwQWk2RkVMeHdR
            OXY1dFM2dk1MVkhkaTJhVnpmVUw0K3pmbDFBCnpBYkRZalF6a1RMd3RmdU55TURC
            UnIyT3NvQmoyUXoxN0tpRWtKRlZsOVUKLS0tIG1KV0R3VkFTK0RHbXNhcU9ObWtl
            NTlEZnVueGZZSTNIVDE1azhLTXJIbWcKMJGOHdJe3xo8f9imKganlzjc4HucMfVo
            8eLQUvCIGdIKm5zXzE5uQSj8YKhkM2br+zB20oyNVIE2d+m3L/19zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T15:29:37Z"
    mac: ENC[AES256_GCM,data:T25moJzgfBWEh5TGy72A9eQS7BRa4OGubOfh1P5LkvHdx5FevI+oA8/l2EMhdcVAb5M/GWrTgVhgmyvi16+JmWwJfg95nguIz8RkXkKnJ8PCRNp1F2qJxYVwA4hsvKnTUB9CP/Ln8+ThycpRvQIIMyZQylrAhsAiZwzJqx0Ie1Q=,iv:+2E7VlcgE2r2h6d66/9BXrQObSXnCo+NbPuAQFAynh8=,tag:G48F/r3wnstrXHCQipxztQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
