apiVersion: v1
kind: Secret
metadata:
    name: symfony_app_secret
    namespace: wallabag
type: Opaque
stringData:
    symfony-secret: ENC[AES256_GCM,data:/SqUd9PZZ7pyTw1Jc+Rt5wV3/vy3MuAWoIxNaiyWImzdJz6J6aAIlSVPhypg9LNz,iv:7ZLm43aFe8NUIITkcTMhfxjHLbVmcl+/94sj9F7yXKE=,tag:Ef0Rxpo2Cv7cRw1tqsJwgQ==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUnM3V2lYeklEci95Z1U2
            eEE2bWJDMWpIZVBSVUVvTUZHYWdxQWdRZ1dRCjEwN0FoNU5uQVFPdk5pZEhLUS9P
            dUpRSVF6YnRTRkZBSWFmMzhpWXNTRzgKLS0tIHhvWTB1T1pYNDc1R3RQblVUL3kz
            enQyVmZEUFdCUlNURkoySkp2NFRwYW8KHNCzxhBTmLbvOFKYAT95MjNGuGu2Qno/
            78CJTLnjGZC0pmzNnKG1hvPXB6BCVcFDORaRAN0mstyDYIY09OGy+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T08:07:53Z"
    mac: ENC[AES256_GCM,data:k+5+F0Qmj8wY9nNzc/l2IM49cjZjfB/fOREkfu/PYsD3UTa8HfJgCSrZxl0VlClBFecRNPP6+YI7Bz6Xm+1DXDZO+c1jyK3kqETZf8x85vJw2YiEmRirHguhazAfArsNFpVgNNpXYdNcfah+q0rJO0EjLt2mQqogoJMpZlP41o0=,iv:FjREc+NFBqA7W1ceKogu9zlFFJKMOoN3E8HNad+jMaI=,tag:9Jed3mOgNG7/t/7ADDO52Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
