apiVersion: apps/v1
kind: Deployment
metadata:
  name: openlist
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openlist
  template:
    metadata:
      labels:
        app: openlist
    spec:
      containers:
        - name: openlist
          image: docker.io/openlistteam/openlist:v4.2.6
          ports:
            - containerPort: 5244
              name: http
          envFrom:
            - secretRef:
                name: openlist
          volumeMounts:
            - name: data
              mountPath: /opt/openlist/data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 5244
            initialDelaySeconds: 10
            periodSeconds: 15
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openlist-data
