apiVersion: v1
kind: Secret
metadata:
    name: k8up-credentials
    namespace: k8up
type: Opaque
stringData:
    repo-password: ENC[AES256_GCM,data:FFXuIrxjQ7TvFXItTuypBm8anesicQ==,iv:Ht3SkUsp7QHdnptE+paOaAdjEUqmzxfKbkZuKc9ElCY=,tag:T7X5CL48GwvMo8ESZABjaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUFVOcFhaK3JnOU53UTZ5
            eGRtakNRY0xxUDZNNW40L283ZzA3VHhjZFRrClJFelFkT2oranhsRFF6SThwdU9i
            eTBUeVZtRVRLRDgxeldrUW1oaW5FQUUKLS0tIHNSbXJnbHUyOW5IMnZCbHhwZnN0
            WE53Uk9zSEZSNDVkS1UrTDVSMDFGR2MKqP+Rc7/GXHZA9BP+rUx3rAejzlh3oAEY
            fi84IYDf/wTZWa135w72k04+G5eesB59N6jAlu4Vq5glFd/XAXBlmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T15:54:54Z"
    mac: ENC[AES256_GCM,data:Ucify7eQEkGOau+1Gq5+MkVYy7ZQVoXnLEMdFLMM/AdUwkO3etbFbBdaGdDwaElN4rGKK+0SLPgOp2KO1HOUoIHcKE9vcVosb0guUye9ABg0xIvJaxGPGDSKbpZFZspE6AKiUgDkwVviBXfe0ZirkdyXmatuxXx5XDKdrQdxRNA=,iv:I/TI7drvUynjuGjb+4/pzjsI01v+O++y4BFvP2tIZQo=,tag:tQq8Ydedcu6RBf4T3m6m0Q==,type:str]
    version: 3.13.3
