apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - cert-manager
  - envoy
  - intel-device-plugins
  - metallb
  - k8up.secret.sops.yaml
  - tailscale.secret.sops.yaml
