apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:q4GHZAi1g7wGIF5fqx7XrWdmfer+kmGKjka5cY39BAnEhuMK/TZXX0YO4erIERwm2U1m0gvPSZ1xNjpJHa/5S+8qRg5ixSuDNsgp+V/P51WlwK11ObfIADlpBcK19FAUJ7d/rA71sZ7RZGHuYusT,iv:TSx8XxgaFRJBeQuwPuViWa6LxxuFIy5/gdtGzvSsMlk=,tag:XMNSBWCm2n9tRSIuQDY20g==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRVFNelJJbFk3cGVIQkJE
            ZGtncVRpVkhyL2ZwbnNNVHRrcFUwOFU1aWpnCk03aDFDZGMvZkZqd09DL3dyOHRR
            QjkxUFA3RFczN0lBWklFaUo3cUNFYXcKLS0tIEUycGFzSUVBdEFkU0gzZE9BT0Nv
            Y2k0d0dkbm5uNXh6N1FNaUhFYysrdDgKbc6afRPdesqPDBoR7npgCK6gZJLtd+FD
            dCZRy9rZ4dxMlvwL0qXx+nmBAhiefmqTkdH/a5iX78yL8IYAZNvdNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T07:43:56Z"
    mac: ENC[AES256_GCM,data:yllHg5pvXPUrHrTSY+iY0MSOaQ3MaWJjGTX8odDdq7+Zu9PbNdQFMI/d2QNwUlNiF3FUclPatAMHkuxMZWH65uEGrXOMleKF5iJGhJHkUE/3C6sAxEVUwbn/5ruF6pSzrmvt1RaO1+Mz6HfnYd9HAyyeErIZDDnRT7YV0bEaY/A=,iv:u4PoY215/OTbPhoiY0v0eSAjJ8T1ru3sszHTYxwNOQQ=,tag:NrYFj49ymXZR9NVWncG7Fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
