---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 24h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.96.5"
      sourceRef:
        kind: HelmRepository
  # values:
  #   operatorConfig:
  #     image:
  #       repository: docker.io/tailscale/k8s-operator
  #   proxyConfig:
  #     image:
  #       repository: docker.io/tailscale/tailscale
  #   oauthSecretVolume:
  #     secret:
  #       secretName: oauth