# infrastructure/configs/k8sgpt-operator/k8sgpt.yaml
---
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-app
  namespace: k8sgpt-operator-system
spec:
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.32
  # noCache: false
  ai:
    enabled: true
    backend: google
    model: gemini-3.1-flash-lite-preview
    secret:
      name: k8sgpt
      key: gemini
  analysis:
    interval: 1m
  filters:
    - Pod
    - Deployment
    - ReplicaSet
    - PersistentVolumeClaim
    - Service
    - StatefulSet
    - Job
    - CronJob
    - Node
    - ValidatingWebhookConfiguration
    - MutatingWebhookConfiguration
    - GatewayClass
    - Gateway
    - HTTPRoute
    # - Ingress
    # - ConfigMap
    # HorizontalPodAutoscaler
    # PodDisruptionBudget
    # NetworkPolicy
    # Log
