apiVersion: v1
kind: Secret
metadata:
    name: k8sgpt
    namespace: k8sgpt-operator-system
type: Opaque
stringData:
    gemini: ENC[AES256_GCM,data:EKzsWIvPo8eU+PeSzYIpP8GNFaeAXDgoGrUqFobmo5FLsO9O5ke8,iv:YQMAdey2tkuoDqj/wbkWyC5bBoDxnDe/18ldte3oXMM=,tag:JsrmSvwYib9xhQVQe9vZHw==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBL2I1NWFQSHhQSHN5TTdl
            eFZSUHFYZHV6aFRjclY4V1RsY2dPV294ejB3Cjc3NU42Y1dLRXUyVmVSWWVoYzRq
            QjNtUUdKVXlqVUtWWGJLSWJLaWYxcncKLS0tIGNqTzZNcUU3b3hIV0FKcDJWVC9x
            RHVEc0dneTN3RGxUV2NqY3Fva3pDeUEKzfaa3I6svvextZSXS/iuwdKKMqmwi4Q6
            tZObMa4B0iAJGKoVNggBp1N1kWb+sbQ2e1T8I1lqWcu9N85qVYQepQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T10:54:39Z"
    mac: ENC[AES256_GCM,data:hoQJtRVhWsAEfz5hl4nfDO7tTRD291NrPfdkliA4PIRDPIMHmYS4dpd8KsdIWNjHmxiioQWNu7elisIJw9txuuObOO0057sxSUm45xkCDhCVoODdbtfXE2QYrIC3zXMkrVVNgqhuDBinoL+Zi6yTSPGHSyfEypx6E1jgQK1UMkI=,iv:YIY+S926YXiJWsvv4J2F6R/sDWUcW43pXzNLmvz8rvM=,tag:2DeheYFrhuMJfrOFTreaOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
