---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: garage
  values:
    config:
      defaultBucket: backup
      capacity: "2Ti"
    auth:
      existingSecret: garage-credentials
    networkPolicy:
      enabled: true
      allowExternal: true
    persistence:
      storageClass: local-path-extdisk
      size: 2Ti
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
