---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 24h
  chart:
    spec:
      chart: bitnami/postgresql
      version: "18.6.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: immich-app/postgres
      tag: 16-vectorchord0.5.3
    primary:
      persistence:
        mountPath: /var/lib/postgresql/data
        size: 2Gi
    common:
      resources:
        preset: "small"
