---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: immich-app/postgres
      tag: 16-vectorchord0.5.3
    global:
      security:
        allowInsecureImages: true
    primary:
      extraEnvVars:
        - name: POSTGRESQL_CONF_DIR
          value: /opt/bitnami/postgresql/conf
      # extraVolumes:
      #   - name: postgre-config
      #     emptyDir: {}
      # extraVolumeMounts:
      #   - name: postgre-config
      #     mountPath: /opt/bitnami/postgresql/conf
      persistence:
        mountPath: /var/lib/postgresql/data
        size: 2Gi
    common:
      resources:
        preset: "small"
