---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-config
  namespace: hermes-agent
data:
  config.yaml: |
    timezone: "Europe/Berlin"
    agent:
      max_turns: 20
    model:
      default: gemini-3-flash-preview
      provider: gemini
      base_url: https://generativelanguage.googleapis.com/v1beta
    fallback_providers:
    - provider: gemini
      model: gemini-3.1-flash-lite
      base_url: https://generativelanguage.googleapis.com/v1beta
    - provider: gemini
      model: gemma-4-31b-it
      base_url: https://generativelanguage.googleapis.com/v1beta
    - provider: gemini
      model: gemma-4-26b-a4b-it
      base_url: https://generativelanguage.googleapis.com/v1beta