---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: hermes-agent
data:
  config.yaml: |
    credential_list:
      - credential_name: gemini_credential
        credential_values:
          api_key: os.environ/GEMINI_API_KEY
          api_base: https://generativelanguage.googleapis.com
          api_version: v1beta
        credential_info:
          description: "gemini gree tier"
          custom_llm_provider: "gemini"
      - credential_name: openrouter_credential
        credential_values:
          api_key: os.environ/OPENROUTER_API_KEY
          api_base: https://openrouter.ai/api
          api_version: v1
        credential_info:
          description: "openrouter credential"
          custom_llm_provider: "openrouter"
    model_list:
      - model_name: gemini
        litellm_params:
          model: gemini/gemini-3-flash-preview
          litellm_credential_name: gemini_credential
          rpm: 5
          tpm: 250000
      - model_name: gemini
        litellm_params:
          model: gemini/gemini-3.1-flash-lite
          litellm_credential_name: gemini_credential
          rpm: 15
          tpm: 250000
      - model_name: gemini
        litellm_params:
          model: gemini/gemma-4-31b-it
          litellm_credential_name: gemini_credential
          rpm: 15
      - model_name: gemini
        litellm_params:
          model: gemini/gemma-4-26b-a4b-it
          litellm_credential_name: gemini_credential
          rpm: 15
      - model_name: owl-alpha
        litellm_params:
          model: openrouter/owl-alpha
          litellm_credential_name: openrouter_credential
      - model_name: nemotron
        litellm_params:
          model: openrouter/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free
          litellm_credential_name: openrouter_credential
    litellm_settings:
      fallbacks: [{"gemini": ["nemotron", "owl-alpha"]}] 
