apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-agent
  namespace: hermes-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes-agent
  template:
    metadata:
      labels:
        app: hermes-agent
    spec:
      containers:
        - name: hermes-agent
          image: docker.io/nousresearch/hermes-agent:sha-e5af1dd6337b3db4eaf16b330f403e08f057a16d
          args: ["gateway", "run"]
          ports:
            - containerPort: 9119
          env:
            - name: HERMES_DASHBOARD
              value: "1"
          envFrom:
          - secretRef:
              name: hermes-agent-env
          securityContext:
            runAsNonRoot: true
            runAsUser: 10000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: data-volume
              mountPath: /opt/data
            - name: config-volume
              mountPath: /opt/data/config.yaml
              subPath: config.yaml
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: hermes-agent-pvc
      - name: config-volume
        configMap:
          name: hermes-config