apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-agent
  namespace: hermes-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes-agent
  template:
    metadata:
      labels:
        app: hermes-agent
    spec:
      containers:
        - name: hermes-agent
          image: docker.io/nousresearch/hermes-agent:v2026.5.16
          args: ["gateway", "run"]
          ports:
            - containerPort: 9119
          env:
            - name: HERMES_DASHBOARD
              value: "1"
            - name: TERMINAL_SSH_KEY
              value: "/opt/data/id_rsa"
          envFrom:
          - secretRef:
              name: hermes-agent-env
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: data-volume
              mountPath: /opt/data
            - name: config-volume
              mountPath: /opt/data/config.yaml
              subPath: config.yaml
            - name: ssh-key-volume
              mountPath: /opt/data/id_rsa
              subPath: id_rsa
              readOnly: true
        - name: litellm
          image: docker.litellm.ai/berriai/litellm:1.84.0
          args:
            - "--config"
            - "/app/proxy_server_config.yaml"
          ports:
          - containerPort: 4000
          volumeMounts:
          - name: litellm-config-volume
            mountPath: /app/proxy_server_config.yaml
            subPath: config.yaml
          envFrom:
          - secretRef:
              name: litellm-env
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
        runAsGroup: 10000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: hermes-agent-pvc
      - name: config-volume
        configMap:
          name: hermes-config
      - name: ssh-key-volume
        secret:
          secretName: hermes-ssh-key
          defaultMode: 0440
      - name: litellm-config-volume
        configMap:
          name: litellm-config