apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-hermes.yaml
  - configmap-litellm.yaml
  - deployment.yaml
  - namespace.yaml
  - pvc.yaml
  - route.yaml
  - secret-env.sops.yaml
  - secret-litellm.sops.yaml
  - secret-sshkey.sops.yaml
  - service.yaml
