apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-env
    namespace: hermes-agent
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:Me5feUZtpNBSMa5HltfrMvhysfCW7sfipiLMJjIyNrAsoeEd1N3K,iv:ozp8uOMAlkfIIeQZtoo2tFHudK4tYnxU+rNmY34BoOY=,tag:ZA6+KyTATO640OmxCm06oQ==,type:str]
    GEMINI_API_KEY_POOL_2: ENC[AES256_GCM,data:cgSPdP94tRSa+bGoFgZ6xRAPjOsCj/mq4FjmD/h99TMl+R0vtUnX,iv:G5wRneq+cLVPPAqJU7okYMnwwobJypCXOKX1xHwE7TM=,tag:o+UucPTVyrubbfkV7QwOoQ==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:SXLV1whVy7gs208hBMZiGiPPoaQ3/9gXaHsu151AlPVrxuc3puAm/SeK5Z9TaAiFRojitLbFM1U9MeXqutZ8PK4mEpl7Pxlx,iv:OssqWY0iQVCNYQmiYo70vUNZK1UJ3FpMxZHMIe3XfN8=,tag:3iQe1FFvgPPgnCls1/Tb0w==,type:str]
    DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:diLzPyO+DgQnmp+GivznaK0K,iv:8w5aM+qj/Ji7SNATLufbpqbGkxcwE8G+md3H6bhtqPA=,tag:H4uzBoFM5jBE6fZ/YRXnJg==,type:str]
    DISCORD_HOME_CHANNEL: ENC[AES256_GCM,data:iWt9TU04uDxXwsXCQ/cv/eqLvQ==,iv:Ia+iZanbkh9inE9BnFrTyv6uodZFYtP/VYqAHgdMdCw=,tag:vUUX0rQvew86qXV2fH0gAg==,type:str]
    DISCORD_HOME_CHANNEL_NAME: ENC[AES256_GCM,data:CNDLij02V63ihhne,iv:3n7jSYSOAt94mIt3zGh8wIsxOYtLXdMsIhS4VUG+2uk=,tag:2kuKD2VfeOZCzrExFKfWvw==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNFJKazQwemtuQXBiNWtO
            VnJyVWYzdjVGcW5qeU1OSHQrWnJiUDROVUNNCjBHRTc3OURsZU4yemdsdnVYYVVz
            WEdkenRTak9NUUQ0ME9ZQk5RaGQrMTgKLS0tIHBXWjNXSXpVMmVXVHcvVzFPYmR5
            WURnMnBuQkhQUlNSUnkrNnJocGZiOE0KoTVCdXa3IbKl+L0DfJs4PJa/6E7lD6vr
            PrulYGboLZ5y5gfewqqImuwejntuKrSwZgRZ6GBwMfBs1kDF4sp2Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T14:06:53Z"
    mac: ENC[AES256_GCM,data:1c7O0hySgpVtVS20ulc0PxN7UO2zSQfD6GEANG+dElKUVF98Q/nq6Guh6r5qXlQy9lUjdtIHS6Q3pN56hW8O9VZHFKKixGWOY5CG8VgACa+ERMrEbuM6cE1UENAfN8W37xIgOXVXONDY4oFQ/ta7+5Dove0G2LH5im8BeqiNC2w=,iv:DyWoLvZT95ySpy2bLyIlrJ0xjOuwBr3XUgObe64yU6I=,tag:wIg4cPaowc8afL0XnkuHDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
