apiVersion: v1
kind: Secret
metadata:
    name: hermes-ssh-key
    namespace: hermes-agent
type: Opaque
stringData:
    id_rsa: ENC[AES256_GCM,data:hIYratsEJYU23vnqxdjr/JY2v5TZvnl8l5IeEnufOlK6Fom8uxlOY1NXUwCAzccD4PNzjq+OJdkofIFcvpElxelyWFG/Qo4YPWOFiw8xZfLAMRy5/7dBOPXbmgIOcU+zHLHOSKwyAymU2q2A/iJugzgh1+fU+cNUpZjZxVnRiID8jrH/oq38QPAbAafKFT+6l4YUiKNAqI0y0l+XssZ49S7k8VFZfYilvotBRlfchb/MNEoPZdmuiY7Ck6bNUnjeQiVqn550i4X4/3cCMgnrqnYZWdUWJByzvrc4i0xFXD1muQwhp93dCOGzTyrUrcTg5k4ZbdPfRfV2ob7Dr/gUm1b8tPTW/E6GpceCZBVh/IkYp6ZOOMJw5D+8VBvjMiG1O1ljSpydrgrSe3ZzAEKOfcZMVk+KIIo5jhv4sGjrFVkSo2Ep6Jc2xq2If9aiOLvVW+up/+tO7zuHQR96EWUhcylgVqMiJlCWd3lLK5HHBTDBbaZolfWjIzPJ2F7rmMMH4dh1,iv:fCFmjYW5Xf4tAYJCiatht0TVPYnSBW4g0vUn+5Kjxos=,tag:mS6J5TV/+zlPFoZM6NxAPw==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeDBSQ3FyemRkN0RNRXRv
            MkNtaWw3OXZlYzE3Lyt3ZGl2UUYrdUhUL1IwCmc2WXZWVnhMbzZ2eE9RY0lzZmRX
            UUtkZGVyUWFMRW5hMGp6RUFWUzVlWXMKLS0tIG1Zb2VyMTE0a1ZFcUpkWnJrMStt
            OW1BZG8rT01rQ0VYQ0tLRnNwMkc1bk0KoGQgUKlYJjXAB5XcrPJIVb0wnfhkvssJ
            kN+9apJvd1xr1ODINYn7oBAitSV/0UoIptVggW7UChHVp4vXV+542A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T11:33:42Z"
    mac: ENC[AES256_GCM,data:K3I/e/cR7LkKu6UwdB94rRlKZtq7p4gq33OcRl98Y5PpWQIr7yscpzUefgjtqSDNXcMqi4SL6sSaEIOqjaReUAsnHb1K3TWzX88rI0T6kq9ePw4eK18Dp/4+zDAW0Tt/t8QgXdcZyNbXUQOX3V3LO6fMkbhElUcZTLpcrkSHR8w=,iv:1lxWmaQt+aFEE0pDDGXp6ki257vmBvTcrcWcItZDecI=,tag:Lw/3KpqEKj4o1xjFQOBRNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
