apiVersion: v1
kind: Secret
metadata:
    name: litellm-env
    namespace: hermes-agent
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:9LhFrE8xlNX6DhsFoVwYC5EVutoX5pL1TApBevCW5Ye/loG4/FCp,iv:TfZkTdF9SKZNeCL4iyokGgBqYiCnuoYPrn/08Yb9UyI=,tag:6YHn2kmpbo6RxDUrUABYQg==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcHE0bnI2S2ZyRVdjTEtN
            NElrOHlGOHRDaXV1d0s3ZDBEWEJRMU5IUjE0CktZRHRVdWlYRUtyeHdjLzNqTWFW
            MlVFVnlGbFRZeGFpZDZZZm92cHlxRXMKLS0tIEEyaGZob2xRdU9SaXZKRDY5YjJJ
            SDZmYytDNmtwV0RSLzNuQ3hIZ0RESzQKuidLQ8GhhyIt0yyvkNQqAReLeFHb5oUv
            9ARZOl1JOfIDl3zGRy5sjWWv5psHp82PTPwuV7knPvWEvjeYeCxlaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T21:44:53Z"
    mac: ENC[AES256_GCM,data:MAlqpfDSBMSw39qI6tHqO4HFukyQAwwQ5ew878OCemlKSHQ8KUSkGPx/Ohaf/+wo75r9dvtGgJaoH8rbmULenTP+kYxUhJiuAZ2il/nUMERI1yJHOnAOK8PSlm6sXrj89kf5zrujW6unhnCfWuaRJNZ7/9hUz8GsYR75FRxnyKU=,iv:ezSy8gRwbpaXFkRoVnOq7VkiyS254FE/kVD0chfTxb8=,tag:8a6LF1c60uui/wV7x2vp4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
