apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-env
    namespace: hermes-agent
type: Opaque
stringData:
    GOOGLE_API_KEY: ENC[AES256_GCM,data:bnenrIV59RMjoJk7GThGf3i8FarFCgV1XvwMtiZj16BXMpr4fd+s,iv:7iEn4czLpQY/VyS1P/WmWqD+H/5z5Ox/MxsIrpZfzRg=,tag:/OLlCdKWgsnnLmx3pbIL8w==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:SXLV1whVy7gs208hBMZiGiPPoaQ3/9gXaHsu151AlPVrxuc3puAm/SeK5Z9TaAiFRojitLbFM1U9MeXqutZ8PK4mEpl7Pxlx,iv:OssqWY0iQVCNYQmiYo70vUNZK1UJ3FpMxZHMIe3XfN8=,tag:3iQe1FFvgPPgnCls1/Tb0w==,type:str]
    DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:diLzPyO+DgQnmp+GivznaK0K,iv:8w5aM+qj/Ji7SNATLufbpqbGkxcwE8G+md3H6bhtqPA=,tag:H4uzBoFM5jBE6fZ/YRXnJg==,type:str]
    DISCORD_HOME_CHANNEL: ENC[AES256_GCM,data:iWt9TU04uDxXwsXCQ/cv/eqLvQ==,iv:Ia+iZanbkh9inE9BnFrTyv6uodZFYtP/VYqAHgdMdCw=,tag:vUUX0rQvew86qXV2fH0gAg==,type:str]
    DISCORD_HOME_CHANNEL_NAME: ENC[AES256_GCM,data:CNDLij02V63ihhne,iv:3n7jSYSOAt94mIt3zGh8wIsxOYtLXdMsIhS4VUG+2uk=,tag:2kuKD2VfeOZCzrExFKfWvw==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNFJKazQwemtuQXBiNWtO
            VnJyVWYzdjVGcW5qeU1OSHQrWnJiUDROVUNNCjBHRTc3OURsZU4yemdsdnVYYVVz
            WEdkenRTak9NUUQ0ME9ZQk5RaGQrMTgKLS0tIHBXWjNXSXpVMmVXVHcvVzFPYmR5
            WURnMnBuQkhQUlNSUnkrNnJocGZiOE0KoTVCdXa3IbKl+L0DfJs4PJa/6E7lD6vr
            PrulYGboLZ5y5gfewqqImuwejntuKrSwZgRZ6GBwMfBs1kDF4sp2Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T08:53:14Z"
    mac: ENC[AES256_GCM,data:rl5EMn8nSG/cWsohqPEsR991JL+hMXXrPqsDKAFi0rhuf9sSa6wVtw78FabCgliw60oERrtA7jtNbl2Gehr3MGR4lltKesg7LjStz6AWCK0AnJYy6CdOljHVFdZ6yIivSQCJrAe4bTk0jAzXE5qaHmuMuNJdxeKQJwMUWNG/gWQ=,iv:bSML7loWMMbib5h319+Y8h3ppV0+ejEZh8zYfjgsJvg=,tag:lw7+69A0IOxqvVf8k8T8lA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
