apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

resources:
  - certificate.yaml
  - gateway.yaml
  - gateway-class.yaml
  - http-https-redirect.yaml
  # disable envoy HTS
  # - policy.yaml 
