apiVersion: "cilium.io/v2"
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-config
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  bgpInstances:
    - name: "instance-65001"
      localASN: 65001
      peers:
        - name: "upstream-route"
          peerASN: 65000
          peerAddress: "10.0.20.1"
          peerConfigRef:
            name: upstream-route-config
