---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-config
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
      - name: adguard-home
        image: adguard/adguardhome:v0.107.74
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: http-ui
          containerPort: 3000
        volumeMounts:
        - name: config-data
          mountPath: /opt/adguardhome/work
        - name: config-conf
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: config-data
        persistentVolumeClaim:
          claimName: adguard-home-config
      - name: config-conf
        persistentVolumeClaim:
          claimName: adguard-home-config
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-ui
  namespace: adguard
spec:
  selector:
    app: adguard-home
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-app
  namespace: adguard
spec:
  parentRefs:
  - name: eg-gateway
    namespace: envoy-gateway-system
    sectionName: https
  hostnames:
  - "dns.${root_domain}"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: adguard-home-ui
      port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns
  namespace: adguard
  annotations:
    metallb.io/loadBalancerIPs: 192.168.20.53
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: adguard-home
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53