---
apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-config
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
      - name: adguard-home
        image: adguard/adguardhome:latest
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: http-ui
          containerPort: 3000 # 初始化界面端口
        - name: http-web
          containerPort: 80   # 运行后的管理界面
        volumeMounts:
        - name: config-data
          mountPath: /opt/adguardhome/work
        - name: config-conf
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: config-data
        persistentVolumeClaim:
          claimName: adguard-home-config
      - name: config-conf
        persistentVolumeClaim:
          claimName: adguard-home-config
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-ui
  namespace: adguard
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-service-group"
    metallb.universe.tf/loadBalancerIPs: 192.168.20.53
spec:
  type: LoadBalancer
  selector:
    app: adguard-home
  ports:
    - name: setup
      port: 3000
      targetPort: 3000
      nodePort: 30000
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns
  namespace: adguard
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-service-group"
    metallb.universe.tf/loadBalancerIPs: 192.168.20.53
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: adguard-home
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53