---
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-app
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    backend: openai
    model: gpt-5.1
    secret:
      name: k8sgpt
      key: openai
  analysis:
    interval: 3m
    namespace: k8sgpt-operator-system
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: k8sgpt-route
#   namespace: k8sgpt-operator-system
# spec:
#   parentRefs:
#   - name: eg-gateway
#     namespace: envoy-gateway-system
#     sectionName: https
#   hostnames:
#   - "k8sgpt.${root_domain}"
#   rules:
#   - backendRefs:
#     - name: k8sgpt-operator-controller-manager-metrics-service
#       port: 8443