---
apiVersion: core.k8sgpt.ai/v1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    backend: openai
    model: gpt-5.1
    secretRef:
      name: k8sgpt
      key: openai
  serve:
    enabled: true
    port: 8080