---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pi-hole
  namespace: flux-system
spec:
  interval: 36h
  url: oci://ghcr.io/helmforgedev/helm/pihole
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "2.x"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pi-hole
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  interval: 24h
  chartRef:
    kind: OCIRepository
    name: pi-hole
    namespace: flux-system
  values:
    admin:
      password: "change-me"
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: "192.168.20.53"
---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: pi-hole
#   namespace: pi-hole
# spec:
#   entryPoints:
#     - websecure
#   routes:
#   - match: Host(`dns.${root_domain}`)
#     kind: Rule
#     services:
#     - name: pi-hole
#       port: 80