apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:wUGPKW0dNUMnMqkFLVLZettKDdaDbCHQm+atM3VfFxMGg/zT1B+iaxL90g0b62FCYNkvOJbytjk=,iv:Up5D/SY8JE7TEBavcpook1uy9h+XE4CSVTXOEMnMxrQ=,tag:WHHGCR6fOpEDAqad5+p0WQ==,type:str]
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSnlmT1UzSStkTGJyTElV
            SkQzK0RBaklMZVhuZ3lWdUs3V013VzdFdHdFCmhZNDd2SElqSmc0M1B6dHU4MjMx
            YnZCNjZ6YWF3YVRNUUlzSWl1dTNxVFEKLS0tIERMekVxVEhhZzF6VE1hd0ZEOFFO
            NEZIcEVBbmpCTk5WUUJLWFlscDVoQkkKdoxdbwPmxSufTIEHVglEZmDlRMkIPHO1
            s3Zw/URPyUXQwb1xieoMWGYc+UsulMfvgu4Qk6BLOAcmkCZu47+Byg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T08:43:05Z"
    mac: ENC[AES256_GCM,data:cGpqeyORjTksp9hoG/HtqvOpg5F3OtYeKtqt5u27AVlLFIedaChMi4/uiwT4W6F1b27jmDEWqRPVmQs83yhDIMjE8yBZwIkkqoaJ3vU8I6q2Byy5vk+uVDIwh08xJf4aas5YgNx0r5iRRAF9aAgBYAnzrbCahVfg7idX32+GspE=,iv:yBs4pZohR1r6CnNK5DQvW6PPajwnaWlDvxna8Jzdj08=,tag:qGxiWMK/auzyQqIwUmVQIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
