apiVersion: v1
kind: Service
metadata:
  name: remote-cluster-a-service
  namespace: external
  annotations:
    tailscale.com/tailnet-fqdn: "example-backend.tail1fce8c.ts.net"
    tailscale.com/proxy-group: "egress-proxies"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
  - port: 80
    targetPort: 80