---
apiVersion: v1
kind: Pod
metadata:
  name: check-pod
  namespace: wallabag
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep", "7200"]
    volumeMounts:
    - name: target-pvc
      mountPath: /mnt/target
  volumes:
  - name: target-pvc
    persistentVolumeClaim:
      claimName: wallabag-data