apiVersion: v1
kind: Pod
metadata:
  name: iperf3-master
  namespace: kube-system
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    command: ['sleep', '3600']