apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: restore
  namespace: database
spec:
  snapshot: "000f26dd"
  restoreMethod:
    folder:
      claimName: postgres-shared-1
  podConfigRef:
    name: podconfig
  backend:
    local:
      mountPath: /mnt/nfs-backup
    volumeMounts:
      - name: nfs-backup
        mountPath: /mnt/nfs-backup