
---
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: manual-pvc-backup-wallabag
  namespace: wallabag
spec:
  podConfigRef:
    name: podconfig
  backend:
    local:
      mountPath: /mnt/nfs-backup
    volumeMounts:
      - name: nfs-backup
        mountPath: /mnt/nfs-backup