---
apiVersion: v1
kind: Pod
metadata:
  name: check-pod
  namespace: database
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep", "7200"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: postgres-shared-1
    # nfs:
    #   server: wifi
    #   path: /mnt/sda1/garage
    #   readOnly: false