apiVersion: v1
kind: Pod
metadata:
  name: memos-migration
  namespace: memos
spec:
  restartPolicy: Never
  containers:
    - name: migrator
      image: ghcr.io/dimitri/pgloader:latest
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: storage
          mountPath: /var/opt/memos
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: memos