apiVersion: v1
kind: Pod
metadata:
  name: migration
  namespace: immich
spec:
  restartPolicy: Never
  containers:
    - name: migrator
      # image: ghcr.io/dimitri/pgloader:latest # for database migration
      image: docker.io/eeacms/rsync:latest
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: src
          mountPath: /src
        - name: dst
          mountPath: /dst
  volumes:
    - name: src
      persistentVolumeClaim:
        claimName: immich-server-pvc
    - name: dst
      persistentVolumeClaim:
        claimName: immich