apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: manual-pvc-restore
  namespace: memos
spec:
  snapshot: "a42ea89da8b8c6cd2457e677c545ef16f69b281c78c6cb465e216ae5f8acf333"
  restoreMethod:
    folder:
      claimName: "memos"
  backend:
    s3:
      bucket: backup
      endpoint: "https://s3.labs123.uk"
      accessKeyIDSecretRef:
          name: s3-credentials
          key: accessKeyID
      secretAccessKeySecretRef:
          name: s3-credentials
          key: secretAccessKey
  # To allow changing the owner of the restored files, we need to run as root.
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0