apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: immich
type: Opaque
stringData:
  accessKeyID: ""
  secretAccessKey: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: wallabag
type: Opaque
stringData:
  accessKeyID: ""
  secretAccessKey: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: memos
type: Opaque
stringData:
  accessKeyID: ""
  secretAccessKey: ""