apiVersion: v1
kind: Secret
metadata:
    name: oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:woludMSF65Fgy6Vcouf+rGI=,iv:IbaFhhezdqwpwDHCBVOKta3loeMlrG7MTJBznahZ0wk=,tag:9NNcN8V8ydr9pU3bRtKWhQ==,type:str]
    client_secret: ENC[AES256_GCM,data:OajaQqT6uDdYcvdJq/RlIj+B/BsMc0MPO2mPPZbgAPcvsjJDAMPLihyL0if59XPeIrWreaRtO+vNSD5IfSyi,iv:+fUEwx9CGHPRFuoJeECGoXmJaG2g5mj77oq7myGVHkQ=,tag:dflY/EUCDX3vb1SNHcKCNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFM3E2eTN1V0R4UGdlRDBn
            VWFlVnY4dUFub1V2NDNSKzZMTWhhaWhoc0MwCkRVQ09Pc3ZjYlFNdkY2bVpXTS9n
            SkY0UkxaT1lubDc1d2dOMU9KQnJGNzgKLS0tIEE2YnJ3U3Bnc05TME03ZWNkcHd6
            Nk1IREZTOVg4K29nWG9zdytFRVhOb3MKEE/XbO17NGkI56CahJt7nsTQ+XClQLd+
            52GGxmftfIBeJK+xtB8+2f4xy8oi7um1VkjIi3oHLtxp4bHCzO9+FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T16:12:28Z"
    mac: ENC[AES256_GCM,data:UP1Q3Io7TF7nWu18KtNf8/vOUihAe7ENKM5elWgiTtsK1l/A4+x6JeJb+nUocRPBnaRwgrGUf/XgtuU/6gguSnPFO1zQe1/Yuywd/BxWzmnUlLKrI3yndzbPG6jtJTW4C2oO0GT7DvJBdDmGiJEEvBC7zylHehKNla7IKkPF2Xc=,iv:MDNmNJJsIKtzKXdebdkprG/AUBsbJJ1ca576hSrMu8g=,tag:BE5IpLXXNZ/zaE5BLUflkQ==,type:str]
    version: 3.13.3
