operatorConfig:
    image:
        repository: ENC[AES256_GCM,data:dh70MhK0v5YXLB5QWM74z+NVBjmKN9ItDvRPdpduqqA=,iv:AYmamenF8kx6dBV1olBM6WQIyprmpkgrDywxFUUtihY=,tag:UJpcKV9reMKdKeLCILqH6w==,type:str]
proxyConfig:
    image:
        repository: ENC[AES256_GCM,data:uo0AoiIzR5ech5CJLC8VHmDSgIMWFYhRySUWJXI=,iv:o9iNUM0Rgs5fvZT0OAgumMX49i94ZbP7GXu9dlFe6pI=,tag:Ms5M0baOKkyfr9EmII5EmA==,type:str]
oauth:
    clientId: ENC[AES256_GCM,data:Mxd2CwF90Egz1xf59IjGlHI=,iv:ksrRbCSFS6F0fIWknJYEAS/eqLjkjunRIItrg8iEk3U=,tag:9aVfbaV0/Ph6tCqdXZMz6Q==,type:str]
    clientSecret: ENC[AES256_GCM,data:JDVEM9hVbTMZgSUK3C67pIMUVtnZ2nid8B8sl6G2IlaZiqvmuqUM4Tcdjm41zy5e6NZ1aeMm7hFSolHMeFqd,iv:dAnRjSA6/P8w4gWyPN1voFzdj1RV/BXeVcibGW3dRG8=,tag:wn3Jq59LCrUKbR5HtZH8gg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1Y4alhRRHUwUStiZmIz
            MUFHd2ZETUk1YmxaZWMxc0U3bjlkeW9CSzFRCi90ZGtQc1pGNHF2RFFoK0tzTmo0
            bzlLa0pvS3Vrd2JBWWtTbW01MnFlTHcKLS0tIGFaL3VpZWVvVkM1cS9YVEJMQWNB
            dEpOQUhXUnFBTkFtOTZqTjQ4WUpLWVUKxT55JWrjvq1D3LiecObe7ZWfgmI9jBV8
            AKRwOeQU5n9UGGpmpt7wz0AFDa91OUNRS98CwBZGUvO9htBSFRkIXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
    lastmodified: "2026-09-30T20:00:22Z"
    mac: ENC[AES256_GCM,data:a7kkVn46hvxvAb4T5tZbP3MrgptKA8bF5xcYOWYXRLUPnZey6YdhwKzZVsMdE8xgCvC2UwDTB9IF1boiApGt/ABJmyS+A5rhlmIK3md2IzxKITkbwnRDJ6QwrXvMyyXPppTeiRrVQB1+ZZMPbLE4SR7bHugPOngL7HwlrO09KWs=,iv:RYRuLdHjTUAhkw2lSfjT6x3AL45poElAcdlDuEPQwNs=,tag:IHQhAKxxS91D0W1XYYY7rQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
