apiVersion: v1
kind: Secret
metadata:
    name: coder-db-credentials
    namespace: coder
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:AUh7jqfb+mjQsw==,iv:Ka83zbPwxBEiRNmW3/6MmL9PettaY94k+y2lJGqJ9Cg=,tag:x7a1reo82D7PPi01wcRJ/w==,type:str]
    password: ENC[AES256_GCM,data:bfBylFnwxOgNr97trqJ2hbI68YDgVq9/5kW5CJUG6VY=,iv:nlMD4FNzoTZLmsGBacCdpL0Jev7rhztG6s5PgjMdh3k=,tag:n2AUTsRbI6IELQh3bKeixA==,type:str]
    db-url: ENC[AES256_GCM,data:dzGgTOjWazuCq6VuYMpvcdJ1cCJs5PmQC+hgJejyefUN4I15/xCOEr8B3XYprCUGrZj4uQUQOHWUm0WOWAwgctDzTWOJ9580wacAMmoudQfSIkjI+PqILZJQ9BlOQrhDtr5VkU7qm7qZUSCzzQ==,iv:tmtFnBAW0DVplqv/hUXBP/y4KDLmDXjqWo7YdokwWxs=,tag:M/Hh6Q1rnX+FHpiIj6fbmg==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRVQxc0JIdUJPSFdPT1dq
            T2tuU1NjM29ZbTVtWEZBMzFTMFZ4NTJ5NWdjCkpVVEM0ek96ajRCZ0dSUFE1b0Zu
            RzFTRitEN05OclRLVG1wcGwrY0M3RzAKLS0tIDNsMDdjNWUyWm5aZkM4ZjVqY25E
            U0hidU1FMWoxNmdmTXcvcmI5R0tSTWsKxZhEVmEnJ8CnEZ5JLeYKDkNf9tutSNvG
            +A+c2UIlkpf7LhuqraYJ8q/L8/uDN9gt5Ao7+BZVV5pdVPQ0qszjjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T10:49:13Z"
    mac: ENC[AES256_GCM,data:xF7+ZsJe/XUkOlaZBNkBeA1ACzfYN9b2q+2px5aTSkrimX9IkedZADz77u3xu8cGQ+gRkDdmBVI4IZ8G1LBJgbVgpMBCdD9DmWwsnXyl6j4CIi98LboQbCqvQVb5hLLLTLVDXL4gUvunU19sJiDvXQQMcGEYPjsmXS/4Oj0MaJ0=,iv:DWvOUFzF1RjwbW5rheVK/jcSpqJgTYdZ+RhDAei10+k=,tag:xrGvPL1hwAy713Xu+Iq8TA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
