apiVersion: v1
kind: Secret
metadata:
    name: oauth2-github
    namespace: coder
type: Opaque
stringData:
    CODER_OAUTH2_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:gCTD5qntWlKuTucQgoVRaz/WU8M=,iv:+juOkDJp6o0hvFf7IrK2YZ2eAMK1B2ARIKOMKuECvr0=,tag:JXY0o2orDUq8XvF3pwyM4Q==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:GFBbv8DlS3A6jS2hMqRLYeYuMBbtq805NHwLsITjhmJ5KjydqeVizw==,iv:KeoX2aFO3Pj/yGJL3or1g9aVlb0DMic6TxOfOX7HICs=,tag:bLOqczT/dDgoFvsd/GOwtg==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bzFicFJQSXYrN3JKOGxz
            eEJFOWZvZnNpeXdyVE8zMWJwWnlwUXRUeEJZCjRqK0xRVjMrOThXUUpZakFTOVlU
            ZGZiNGJyQWRIUWNSVkoza3oxaXIxNFEKLS0tIGQzOTJ1MjVFNElPWEliMWJvT29K
            V21LeUdZODFpV2JHd0tRcHVSWE5MUG8K9rAPBzIkNdsmSksVnIcOtFr1+d+RxqpK
            6iWZ6t3rn/yoohCW2ewAqx9o9AekBm/HlUSPYU/hNbretMJ022HAOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T12:35:43Z"
    mac: ENC[AES256_GCM,data:sjf0UnU423FFAjy54e4qSsn73ziEmgIyOj4pnKkFhDo7X7ZU6wREt7+5/JhR+q4TQt93IlkhZBctYmVyFvqqWMndjXOxXTaEJTJO4WY24nb/ZUkBnpYupQuOgdTFAQfpvrzlF9ASlemr00R8RlVPuMVmsUUpoBHPtxmsfvivb3s=,iv:ztLxdvNjXekbzvC6A+ZGHwNb3cxEnc0tfkjNECxuFG0=,tag:Vv7qDzGbYZoZuY2LNDbfCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
