apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-data
  namespace: wallabag
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi